apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supportplane.fullname" . }}-secrets
  labels:
    {{- include "supportplane.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.secrets.postgres.database }}
  POSTGRES_USER: {{ .Values.secrets.postgres.username }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgres.password }}
  KEYCLOAK_ADMIN: {{ .Values.secrets.keycloak.adminUsername }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.secrets.keycloak.adminPassword }}
