{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supportplane.fullname" . }}-secrets
  labels:
    {{- include "supportplane.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.secrets.postgres.database | quote }}
  POSTGRES_USER: {{ .Values.secrets.postgres.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgres.password | quote }}
  KEYCLOAK_ADMIN: {{ .Values.secrets.keycloak.adminUsername | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.secrets.keycloak.adminPassword | quote }}
  APP_ENCRYPTION_KEY: {{ .Values.secrets.appEncryptionKey | quote }}
  {{- if .Values.clickhouse.enabled }}
  CLICKHOUSE_USER: {{ .Values.clickhouse.auth.username | quote }}
  CLICKHOUSE_PASSWORD: {{ .Values.clickhouse.auth.password | quote }}
  {{- end }}
{{- end }}
