-- V10: Production hardening, pipeline reliability, storage optimization,
-- query optimization, observability, DR deep, cost optimization, developer experience.

INSERT INTO recommendation_rules (code, title, description, category, subcategory, component, threat, vulnerability, asset, impact, default_likelihood, default_severity, recommendations_text, condition) VALUES

-- ============================================================
-- PRODUCTION HARDENING: CONNECTION POOLING & TIMEOUTS
-- ============================================================

('CONN-POOL-HS2', 'HiveServer2 connection pool tuning',
 'HS2 thread pool and connection limits must be sized for concurrent user sessions.',
 'Performance', 'Hive', 'Hive',
 '["Connection refused", "Query queuing"]', '["Default thread pool too small"]', '["Hive"]',
 'Default 100 threads exhausted under heavy BI workloads, blocking new connections.',
 'MEDIUM', 'WARNING',
 '["Set hive.server2.thrift.max.worker.threads=500", "Set hive.server2.thrift.min.worker.threads=5", "Configure hive.server2.session.check.interval=6h for session cleanup", "Monitor active connections via JMX"]',
 '{"type": "always"}'),

('CONN-POOL-HBASE-CLIENT', 'HBase client connection tuning',
 'HBase client timeout and retry settings prevent cascading failures from slow RegionServers.',
 'Performance', 'HBase', 'HBase',
 '["Cascading timeouts", "Application hangs"]', '["Default timeouts too high"]', '["HBase"]',
 'Default 60s RPC timeout causes threads to block for minutes during RS failures.',
 'MEDIUM', 'WARNING',
 '["Set hbase.rpc.timeout=30000 (30s)", "Set hbase.client.retries.number=5", "Set hbase.client.pause=100 (ms between retries)", "Set hbase.client.operation.timeout=60000 for compound operations"]',
 '{"type": "always"}'),

('TIMEOUT-HDFS-CLIENT', 'HDFS client timeout configuration',
 'HDFS client socket and RPC timeouts prevent indefinite hangs during DataNode failures.',
 'Performance', 'HDFS', 'HDFS',
 '["Client hangs on dead DataNode"]', '["Default timeout too long"]', '["HDFS"]',
 'Without proper timeouts, clients wait indefinitely for unresponsive DataNodes.',
 'LOW', 'WARNING',
 '["Set dfs.client.socket-timeout=60000 (60s)", "Set ipc.client.connect.timeout=20000", "Set ipc.client.connect.max.retries.on.timeouts=3", "Set dfs.client.failover.max.attempts=15 for HA"]',
 '{"type": "always"}'),

('THREADPOOL-HDFS-DN', 'DataNode thread pool configuration',
 'DataNode transfer thread pool limits concurrent block transfers and affects throughput.',
 'Performance', 'HDFS', 'HDFS',
 '["Block transfer bottleneck"]', '["Default thread pool too small for large clusters"]', '["HDFS"]',
 'Under-sized pool causes block transfer queuing, slowing replication and client reads.',
 'LOW', 'WARNING',
 '["Set dfs.datanode.max.transfer.threads=8192 (default 4096)", "Monitor DataNode xceiver count via JMX", "Increase for clusters with >100 concurrent jobs"]',
 '{"type": "always"}'),

('RETRY-POLICY-ETL', 'ETL retry and backoff strategy',
 'ETL jobs should implement retry with exponential backoff to handle transient failures gracefully.',
 'Operations', 'Pipeline', 'Platform',
 '["Job failures from transient errors", "Retry storms"]', '["No retry or aggressive retries"]', '["Yarn", "Hive"]',
 'No retry causes unnecessary failures; aggressive retry without backoff creates thundering herd.',
 'MEDIUM', 'WARNING',
 '["Implement exponential backoff: initial=1s, multiplier=2, max=60s, jitter=25%", "Set max retries: 3-5 for idempotent operations", "Use Oozie retry-max/retry-interval for workflow actions", "Implement dead letter queue for permanently failed records"]',
 '{"type": "always"}'),

('DEAD-LETTER-QUEUE', 'Dead letter queue for failed processing',
 'Records that fail processing repeatedly should be routed to a DLQ for investigation instead of blocking the pipeline.',
 'Operations', 'Pipeline', 'Kafka',
 '["Pipeline blocked by poison messages", "Data loss from dropped records"]', '["No DLQ pattern"]', '["Kafka", "NiFi"]',
 'A single malformed record can block an entire consumer group indefinitely without DLQ.',
 'MEDIUM', 'WARNING',
 '["Create DLQ topic for each consumer: topic-name.dlq", "Route records to DLQ after N retry failures", "Monitor DLQ size and alert on growth", "Implement DLQ replay mechanism for reprocessing"]',
 '{"type": "always"}'),

-- ============================================================
-- DATA PIPELINE RELIABILITY
-- ============================================================

('PIPELINE-IDEMPOTENCY', 'ETL job idempotency',
 'ETL jobs must produce the same result when re-run, enabling safe retries and reprocessing.',
 'Operations', 'Pipeline', 'Platform',
 '["Duplicate data from re-runs", "Incorrect aggregations"]', '["Non-idempotent writes"]', '["Data"]',
 'Non-idempotent jobs create duplicates when retried after partial failure.',
 'HIGH', 'WARNING',
 '["Use INSERT OVERWRITE (not INSERT INTO) for Hive batch loads", "Use upsert/merge for incremental loads", "Use Kafka exactly-once for streaming with enable.idempotence=true", "Track job watermarks to detect and prevent re-processing"]',
 '{"type": "always"}'),

('PIPELINE-FRESHNESS-SLA', 'Data freshness SLA per dataset',
 'Each critical dataset should have a defined freshness target (max age of data).',
 'Operations', 'Pipeline', 'Platform',
 '["Stale data in reports"]', '["No freshness monitoring"]', '["Data"]',
 'Stakeholders making decisions on stale data without knowing it is stale.',
 'MEDIUM', 'WARNING',
 '["Define freshness SLA per table: CRITICAL < 1h, STANDARD < 24h, ARCHIVE < 7d", "Implement freshness check: compare max(event_timestamp) vs now()", "Alert when freshness breaches SLA", "Display freshness on data catalog entries"]',
 '{"type": "always"}'),

('PIPELINE-LATENCY-E2E', 'End-to-end pipeline latency tracking',
 'Measure time from data ingestion to availability for querying.',
 'Operations', 'Pipeline', 'Platform',
 '["Unknown pipeline delays"]', '["No latency measurement"]', '["Data"]',
 'Without E2E latency tracking, degradation is invisible until users complain.',
 'MEDIUM', 'WARNING',
 '["Inject timestamp at ingestion, record at each transformation stage", "Compare ingestion timestamp vs query-ready timestamp", "Track p50/p95/p99 latency trends", "Set SLA: e.g., p95 E2E latency < 30 minutes for daily refresh"]',
 '{"type": "always"}'),

('PIPELINE-DEPS-TRACKING', 'Pipeline dependency tracking',
 'Pipeline dependencies must be tracked to propagate failure alerts and enable impact analysis.',
 'Operations', 'Pipeline', 'Platform',
 '["Silent downstream failures"]', '["No dependency graph"]', '["Data"]',
 'When upstream job fails, downstream jobs run on stale data without anyone knowing.',
 'MEDIUM', 'WARNING',
 '["Map dependencies in Oozie coordinator or Airflow DAGs", "Implement data-ready sensors (check partition exists before processing)", "Propagate failure notifications downstream", "Visualize pipeline dependency graph"]',
 '{"type": "always"}'),

('SCHEMA-COMPAT-ENFORCE', 'Schema compatibility enforcement',
 'Schema changes must be validated for backward/forward compatibility before deployment.',
 'Governance', 'Data Management', 'Kafka',
 '["Consumer breakage from incompatible schema"]', '["No compatibility checks"]', '["Kafka", "Data"]',
 'Adding a required field without default breaks all existing consumers.',
 'HIGH', 'CRITICAL',
 '["Use Schema Registry with compatibility mode: BACKWARD (safe default)", "Test schema changes in CI/CD before deployment", "For Avro: always add new fields with defaults, never remove required fields", "For Parquet/ORC: test read compatibility with older files"]',
 '{"type": "always"}'),

('STREAM-WATERMARK', 'Streaming watermark and late data handling',
 'Streaming jobs must define watermarks and late data policies to handle out-of-order events.',
 'Operations', 'Pipeline', 'Kafka',
 '["Incorrect window aggregations", "Missing late events"]', '["No watermark configured"]', '["Kafka", "Spark"]',
 'Without watermarks, streaming windows either wait forever or drop late events silently.',
 'MEDIUM', 'WARNING',
 '["Configure watermark in Spark Structured Streaming: withWatermark(eventTime, 10 minutes)", "Set allowed lateness for windows", "Route late data to separate processing path", "Monitor watermark lag vs event time skew"]',
 '{"type": "always"}'),

-- ============================================================
-- STORAGE OPTIMIZATION
-- ============================================================

('FILEFORMAT-SELECTION', 'File format selection per use case',
 'Different workloads require different file formats. Parquet for analytics, ORC for ACID, Avro for streaming.',
 'Performance', 'Data Management', 'HDFS',
 '["Suboptimal query performance", "Storage waste"]', '["One format for all data"]', '["HDFS", "Data"]',
 'Using text/CSV for analytical tables is 10-100x slower than columnar formats.',
 'MEDIUM', 'WARNING',
 '["Analytical queries (Impala, Spark SQL): Parquet with Snappy", "Transactional tables (Hive ACID): ORC", "Streaming/CDC: Avro with Schema Registry", "Logs/raw ingestion: text/JSON → convert to Parquet on landing", "Never use text/CSV for production analytical tables"]',
 '{"type": "always"}'),

('PARTITION-STRATEGY', 'Table partitioning strategy',
 'Partition design must balance query pruning efficiency with partition count overhead.',
 'Performance', 'Data Management', 'Hive',
 '["Full table scans", "Partition explosion"]', '["No or wrong partitioning"]', '["Hive", "HDFS"]',
 'Unpartitioned tables require full scans. Over-partitioned tables overwhelm the Metastore.',
 'MEDIUM', 'WARNING',
 '["Partition by query filter predicates (usually date)", "Rule of thumb: each partition should be >128MB", "Avoid multi-level partitioning beyond 2-3 levels", "Set hive.exec.max.dynamic.partitions.pernode=100 as safety limit"]',
 '{"type": "always"}'),

('COMPACTION-HIVE', 'Hive ACID table compaction',
 'ACID tables accumulate delta files that must be compacted for read performance.',
 'Performance', 'Hive', 'Hive',
 '["Degraded read performance"]', '["Compaction not running or behind"]', '["Hive"]',
 'Without compaction, each query reads base + all deltas, degrading exponentially with updates.',
 'MEDIUM', 'WARNING',
 '["Enable initiator: hive.compactor.initiator.on=true on one HS2", "Set hive.compactor.worker.threads=4", "Set hive.compactor.delta.pct.threshold=0.1 for minor compaction trigger", "Monitor compaction queue: SHOW COMPACTIONS"]',
 '{"type": "always"}'),

('STORAGE-POLICY-HDFS', 'HDFS storage policies per directory',
 'HDFS storage policies (HOT, WARM, COLD, ALL_SSD) optimize cost by matching storage media to data temperature.',
 'Performance', 'HDFS', 'HDFS',
 '["Storage cost", "Suboptimal I/O performance"]', '["Default ONE_SSD or HOT for everything"]', '["HDFS"]',
 'Storing cold data on SSDs wastes expensive media; storing hot data on archive disks kills performance.',
 'LOW', 'INFO',
 '["Set HOT (3x DISK) for frequently accessed data", "Set WARM (1x DISK + 2x ARCHIVE) for infrequent access", "Set COLD (3x ARCHIVE) for rarely accessed data", "Use hdfs storagepolicies command to assign per directory"]',
 '{"type": "always"}'),

('SMALLFILE-CONSOLIDATION', 'Small file consolidation job',
 'A scheduled job should merge small files into larger ones to reduce NameNode pressure.',
 'Performance', 'HDFS', 'HDFS',
 '["NameNode memory exhaustion"]', '["No consolidation process"]', '["HDFS"]',
 'Small files accumulate daily from streaming ingestion and partition writes.',
 'MEDIUM', 'WARNING',
 '["Schedule daily/weekly compaction: INSERT OVERWRITE SELECT * FROM table", "Use Hive CONCATENATE: ALTER TABLE table CONCATENATE", "Configure Hive merge: hive.merge.mapredfiles=true, hive.merge.smallfiles.avgsize=256000000", "Monitor average file size per table/directory"]',
 '{"type": "always"}'),

-- ============================================================
-- QUERY OPTIMIZATION
-- ============================================================

('QUERY-ADMISSION-POOLS', 'Query admission control resource pools',
 'Resource pools separate interactive, batch, and ETL workloads with distinct memory and concurrency limits.',
 'Performance', 'Query', 'Impala',
 '["Resource contention between workload types"]', '["Single default pool"]', '["Impala", "Yarn"]',
 'Without pools, a single large ETL query can consume all memory, blocking interactive BI.',
 'MEDIUM', 'WARNING',
 '["Create pools: interactive (low latency, limited mem), batch (high mem, queuing OK), etl (scheduled, high parallelism)", "Set per-pool max memory and max concurrent queries", "Configure queue timeout per pool", "Route queries via pool hints or user-to-pool mapping"]',
 '{"type": "always"}'),

('MATERIALIZED-VIEWS', 'Materialized views for common aggregations',
 'Materialized views pre-compute expensive aggregations, reducing query latency from minutes to seconds.',
 'Performance', 'Query', 'Hive',
 '["Repeated expensive computation"]', '["No pre-computed aggregations"]', '["Hive"]',
 'Common dashboards re-compute the same GROUP BY daily, wasting cluster resources.',
 'LOW', 'INFO',
 '["Identify top-N most expensive recurring queries", "Create materialized views for common aggregations", "Schedule MV refresh after underlying data updates", "Hive 3.x+ supports automatic MV rewriting for matching queries"]',
 '{"type": "always"}'),

('STATS-FRESHNESS', 'Table statistics freshness',
 'Stale statistics cause the optimizer to choose suboptimal query plans.',
 'Performance', 'Query', 'Hive',
 '["Suboptimal query plans"]', '["Outdated statistics"]', '["Hive", "Impala"]',
 'After major data loads, statistics no longer reflect actual data distribution.',
 'MEDIUM', 'WARNING',
 '["Run ANALYZE TABLE after every major data load (>10% data change)", "Schedule nightly COMPUTE STATS for Impala on key tables", "Enable hive.stats.autogather=true for new inserts", "Monitor stats age vs last data modification time"]',
 '{"type": "always"}'),

('HBASE-SECONDARY-INDEX', 'HBase secondary index pattern',
 'HBase only supports primary key lookups. Secondary access patterns need index tables or Phoenix.',
 'Performance', 'HBase', 'HBase',
 '["Full table scans for non-rowkey queries"]', '["No secondary access strategy"]', '["HBase"]',
 'Without secondary indexes, non-rowkey queries require full table scan — extremely slow.',
 'LOW', 'INFO',
 '["Use Apache Phoenix for automatic secondary index management", "For manual approach: maintain separate index tables with reversed key mapping", "Consider global vs local indexes based on query patterns", "Monitor index consistency if using manual index tables"]',
 '{"type": "always"}'),

-- ============================================================
-- MONITORING & OBSERVABILITY
-- ============================================================

('OBS-DISTRIBUTED-TRACING', 'Distributed tracing integration',
 'Distributed tracing enables following a request across multiple services for root cause analysis.',
 'Operations', 'Monitoring', 'Platform',
 '["Cannot trace cross-service issues"]', '["No tracing infrastructure"]', '["Servers"]',
 'Without tracing, diagnosing latency in a multi-hop pipeline (Kafka→Spark→Hive→Impala) is guesswork.',
 'LOW', 'INFO',
 '["Deploy Jaeger or Zipkin for trace collection", "Integrate OpenTelemetry agents with Spark, Hive, and custom services", "Propagate trace context through Kafka headers", "Use trace data to identify bottleneck services"]',
 '{"type": "always"}'),

('OBS-PIPELINE-METRICS', 'Pipeline health metrics export',
 'Each data pipeline should export metrics: rows processed, errors, runtime, data age.',
 'Operations', 'Monitoring', 'Platform',
 '["Silent pipeline failures"]', '["No pipeline-level metrics"]', '["Data"]',
 'Service-level metrics show cluster health but miss pipeline-level problems (wrong data, slow transform).',
 'MEDIUM', 'WARNING',
 '["Export metrics from each pipeline stage: input rows, output rows, error count, runtime", "Publish to Prometheus/Grafana alongside cluster metrics", "Create pipeline dashboards per data product", "Alert on: error rate >1%, runtime >2x baseline, zero output rows"]',
 '{"type": "always"}'),

('OBS-ANOMALY-DETECTION', 'Metric anomaly detection',
 'Anomaly detection identifies unusual patterns that static thresholds miss.',
 'Operations', 'Monitoring', 'Platform',
 '["Subtle degradation undetected"]', '["Only static threshold alerts"]', '["Servers"]',
 'Static thresholds miss gradual degradation and seasonal patterns.',
 'LOW', 'INFO',
 '["Implement baseline + deviation detection for key metrics", "Track: query latency p99, HDFS throughput, YARN queue wait time, Kafka consumer lag", "Use tools: Prometheus alertmanager with recording rules, Grafana ML-based alerts", "Start with 3-sigma deviation from 7-day rolling average"]',
 '{"type": "always"}'),

('OBS-PERF-REGRESSION', 'Performance regression detection',
 'Query and job runtimes should be tracked to detect performance regressions after changes.',
 'Operations', 'Monitoring', 'Platform',
 '["Undetected performance regression"]', '["No baseline tracking"]', '["Servers"]',
 'Config changes or data growth can silently degrade performance by 2-10x.',
 'MEDIUM', 'WARNING',
 '["Benchmark key queries monthly and record baseline times", "Alert when query time exceeds 2x baseline", "Track Spark job runtimes in History Server", "Compare performance before/after config changes"]',
 '{"type": "always"}'),

-- ============================================================
-- DISASTER RECOVERY
-- ============================================================

('DR-REPLICATION-LAG', 'Cross-DC replication lag monitoring',
 'Replication lag between primary and DR site determines actual RPO.',
 'Architecture', 'Disaster Recovery', 'Platform',
 '["RPO exceeded during failover"]', '["Replication lag unmonitored"]', '["Data"]',
 'If replication lags by 6 hours, actual RPO is 6 hours regardless of what the DR plan says.',
 'HIGH', 'CRITICAL',
 '["Monitor distcp lag for HDFS (time since last successful sync)", "Monitor HBase replication lag via JMX: replicationLag metric", "Monitor Kafka MirrorMaker consumer lag", "Alert when lag exceeds RPO target"]',
 '{"type": "always"}'),

('DR-RESTORE-DRILL', 'Backup restoration drill',
 'Quarterly backup restore tests validate that backups are actually usable.',
 'Architecture', 'Disaster Recovery', 'Platform',
 '["Backups corrupted or incomplete"]', '["Backups never tested"]', '["Data"]',
 'Untested backups are wishes, not backups. Corruption, missing files, and schema drift cause restore failures.',
 'HIGH', 'CRITICAL',
 '["Schedule quarterly restore drills: restore to isolated test environment", "Verify: data completeness (row counts), data integrity (checksums), query accuracy", "Time the restore and compare to RTO SLA", "Document and fix any issues found during drills"]',
 '{"type": "always"}'),

('DR-RPO-RTO-ACTUAL', 'Actual RPO/RTO measurement',
 'Actual RPO and RTO must be measured, not assumed, through periodic testing.',
 'Architecture', 'Disaster Recovery', 'Platform',
 '["DR plan SLAs not achievable"]', '["Assumed RPO/RTO never validated"]', '["Data"]',
 'Documented RPO=1h/RTO=4h means nothing if actual restore takes 24h with 6h data loss.',
 'HIGH', 'CRITICAL',
 '["Measure actual RPO: replication lag during normal operations", "Measure actual RTO: time from failure declaration to full service restoration", "Compare actual vs target quarterly", "Update DR plan if gaps exist between actual and target"]',
 '{"type": "always"}'),

-- ============================================================
-- COST OPTIMIZATION
-- ============================================================

('COST-RIGHTSIZE-NODES', 'Node right-sizing',
 'Nodes with consistently low utilization should be downsized or decommissioned.',
 'Operations', 'Cost', 'Platform',
 '["Wasted infrastructure budget"]', '["Over-provisioned nodes"]', '["Servers"]',
 'Nodes running at <30% utilization for months waste budget that could fund improvements.',
 'LOW', 'WARNING',
 '["Track 30-day average CPU, memory, disk utilization per node", "Flag nodes with all metrics <30% for right-sizing review", "Consider decommissioning DataNodes if HDFS utilization is low", "Consolidate underutilized services onto fewer nodes"]',
 '{"type": "always"}'),

('COST-IDLE-RESOURCES', 'Idle resource detection',
 'Unused YARN queues, empty tables, orphaned topics, and abandoned jobs waste resources.',
 'Operations', 'Cost', 'Platform',
 '["Resource waste"]', '["No idle resource tracking"]', '["Yarn", "HDFS", "Kafka"]',
 'Idle resources accumulate over years as projects end but infrastructure remains.',
 'LOW', 'WARNING',
 '["Scan for: YARN queues with 0 jobs in 30 days, Hive tables with 0 queries in 90 days", "Detect Kafka topics with 0 consumers and stale offsets", "Identify HDFS directories with no access in 180 days", "Generate monthly idle resource report for team review"]',
 '{"type": "always"}'),

('COST-COMPRESSION-SAVINGS', 'Compression savings analysis',
 'Analyze storage savings from compression and identify uncompressed datasets.',
 'Operations', 'Cost', 'HDFS',
 '["Storage waste from uncompressed data"]', '["No compression analysis"]', '["HDFS"]',
 'Large uncompressed text/CSV datasets waste 3-10x storage compared to compressed Parquet.',
 'LOW', 'INFO',
 '["Identify tables using text/CSV format and estimate compressed size", "Calculate savings: typical Parquet+Snappy is 3-5x compression vs text", "Prioritize largest uncompressed tables for conversion", "Track compression ratio as a cluster-wide metric"]',
 '{"type": "always"}'),

('COST-CLOUD-TIERING', 'Cloud storage tiering for cold data',
 'Cold data on premium storage (SSD, local HDFS) should be moved to cheaper cloud tiers.',
 'Operations', 'Cost', 'HDFS',
 '["Excessive storage costs"]', '["All data on same storage tier"]', '["HDFS", "Data"]',
 'Data accessed once per quarter does not need NVMe performance — archive tier costs 10-50x less.',
 'LOW', 'INFO',
 '["Identify data access patterns: hot (daily), warm (weekly), cold (monthly), archive (yearly)", "Move cold data to S3/ADLS/GCS using distcp or HDFS tiered storage", "For cloud: S3 Standard → S3 IA → S3 Glacier based on access frequency", "Maintain metadata in Hive pointing to external storage locations"]',
 '{"type": "always"}'),

-- ============================================================
-- DEVELOPER EXPERIENCE & CI/CD
-- ============================================================

('DEV-CICD-PIPELINES', 'CI/CD for data pipelines',
 'Data pipelines should be deployed through CI/CD with automated testing, not manual deployment.',
 'Operations', 'DevOps', 'Platform',
 '["Inconsistent deployments", "Untested changes in production"]', '["Manual deployment"]', '["Data"]',
 'Manual deployment is error-prone and lacks audit trail.',
 'MEDIUM', 'WARNING',
 '["Version control all pipeline code (Spark, Hive, Oozie workflows)", "Implement CI pipeline: lint → unit test → integration test → deploy to staging → deploy to prod", "Use Oozie bundles or Airflow DAG versioning for deployment", "Require approval gates between staging and production"]',
 '{"type": "always"}'),

('DEV-TESTING-FRAMEWORK', 'Data pipeline testing',
 'ETL logic should have unit tests (transformation logic) and integration tests (end-to-end).',
 'Operations', 'DevOps', 'Platform',
 '["Bugs deployed to production"]', '["No automated testing"]', '["Data"]',
 'Without tests, every deployment is a gamble — bugs are found in production by users.',
 'MEDIUM', 'WARNING',
 '["Unit test transformations with sample data (Spark: spark-testing-base, Python: pytest)", "Integration test with real data subset in staging environment", "Validate output schema, row counts, null rates, key uniqueness after each run", "Run tests in CI before merge to main branch"]',
 '{"type": "always"}'),

('DEV-ENV-PARITY', 'Dev/staging environment parity',
 'Development and staging environments should mirror production configuration.',
 'Operations', 'DevOps', 'Platform',
 '["Works in dev, fails in prod"]', '["Configuration drift between environments"]', '["Servers"]',
 'Config differences between dev and prod cause deployment failures and incorrect behavior.',
 'LOW', 'WARNING',
 '["Use infrastructure-as-code (Ambari blueprints, Ansible) for consistent provisioning", "Mirror production configs in staging (minus scale)", "Use production data samples in staging (anonymized)", "Validate config parity as part of deployment checklist"]',
 '{"type": "always"}'),

('DEV-CODE-REVIEW', 'Code review for pipeline changes',
 'All data pipeline changes should be peer-reviewed before deployment.',
 'Operations', 'DevOps', 'Platform',
 '["Logic errors in production"]', '["No code review requirement"]', '["Data"]',
 'A single reviewer catches obvious mistakes: wrong join type, missing filter, broken idempotency.',
 'MEDIUM', 'WARNING',
 '["Require PR approval for all pipeline code changes", "Review checklist: idempotency, error handling, monitoring, backward compatibility", "Require at least one domain-expert reviewer", "Use automated checks: SQL lint, schema validation, test coverage"]',
 '{"type": "always"}'),

('DEV-DOC-STANDARDS', 'Dataset and pipeline documentation',
 'Every production dataset and pipeline should have documentation: purpose, schema, owner, SLA, dependencies.',
 'Operations', 'DevOps', 'Platform',
 '["Tribal knowledge dependency"]', '["No documentation standards"]', '["Data"]',
 'Without docs, team members leaving takes institutional knowledge with them.',
 'LOW', 'WARNING',
 '["Document in Atlas/data catalog: description, owner, freshness SLA, classification", "Document pipeline in README: architecture, dependencies, error handling, runbook link", "Enforce documentation in PR review checklist", "Track documentation coverage as a team metric"]',
 '{"type": "always"}'),

-- ============================================================
-- ADDITIONAL DEEP RULES
-- ============================================================

('METADATA-CONSISTENCY', 'Hive Metastore vs HDFS consistency',
 'Metastore table definitions can become inconsistent with actual HDFS data (missing partitions, orphan files).',
 'Operations', 'Data Management', 'Hive',
 '["Query failures", "Missing data"]', '["No consistency checks"]', '["Hive", "HDFS"]',
 'HDFS partitions added/removed without updating Metastore cause query errors or missing data.',
 'MEDIUM', 'WARNING',
 '["Run MSCK REPAIR TABLE periodically to sync partitions", "Check for orphan HDFS directories not registered in Metastore", "Implement post-ETL partition registration as part of pipeline", "Schedule weekly consistency check for critical tables"]',
 '{"type": "always"}'),

('KAFKA-CONSUMER-MONITORING', 'Kafka consumer group monitoring',
 'All consumer groups should be monitored for lag, rebalancing frequency, and member health.',
 'Operations', 'Monitoring', 'Kafka',
 '["Consumer failures undetected"]', '["No consumer-level monitoring"]', '["Kafka"]',
 'A failed consumer causes growing lag silently until downstream systems serve stale data.',
 'HIGH', 'WARNING',
 '["Monitor lag per consumer group: kafka-consumer-groups.sh --describe", "Alert on: lag growing over 3 consecutive checks, empty consumer group, frequent rebalances", "Track consumer throughput: records/sec per partition", "Monitor JMX: kafka.consumer.fetch-manager-metrics"]',
 '{"type": "always"}'),

('SPARK-DRIVER-MEM', 'Spark driver memory sizing',
 'Driver memory must be sized for the largest collect/broadcast and for SparkContext overhead.',
 'Performance', 'Spark', 'Spark',
 '["Driver OOM", "Broadcast failures"]', '["Default 1g driver memory"]', '["Spark"]',
 'Driver collects broadcast tables and query plans. Large broadcasts or complex plans exceed default memory.',
 'MEDIUM', 'WARNING',
 '["Set spark.driver.memory=2g-8g based on broadcast sizes and plan complexity", "Set spark.driver.maxResultSize=2g for large collect() operations", "Never use collect() on large datasets — use write/save instead", "Monitor driver memory in Spark UI Environment tab"]',
 '{"type": "always"}'),

('SPARK-MEMORY-MGMT', 'Spark unified memory management',
 'Spark unified memory model balances execution (shuffle, sort) and storage (cache) dynamically.',
 'Performance', 'Spark', 'Spark',
 '["Excessive spilling or cache eviction"]', '["Default memory fractions not optimal"]', '["Spark"]',
 'Wrong memory fractions cause either excessive spilling (slow) or cache eviction (repeated I/O).',
 'LOW', 'INFO',
 '["Default spark.memory.fraction=0.6 works for most workloads", "Increase spark.memory.storageFraction=0.5 for cache-heavy workloads (iterative ML)", "Decrease storage fraction for shuffle-heavy workloads (large joins)", "Monitor storage and execution memory in Spark UI Executors tab"]',
 '{"type": "always"}'),

('HIVE-COMPACTOR-THREADS', 'Hive compactor worker threads',
 'Insufficient compactor threads cause delta file accumulation in ACID tables.',
 'Performance', 'Hive', 'Hive',
 '["Read degradation from delta accumulation"]', '["Default single compactor thread"]', '["Hive"]',
 'With one thread, compaction for hundreds of partitions falls behind write rate.',
 'MEDIUM', 'WARNING',
 '["Set hive.compactor.worker.threads=4-8 based on cluster size", "Enable on one HS2: hive.compactor.initiator.on=true", "Monitor: SHOW COMPACTIONS — look for growing queue", "Schedule major compactions during off-peak hours"]',
 '{"type": "always"}'),

('ZK-SESSION-TIMEOUT', 'ZooKeeper session timeout tuning',
 'Service session timeouts with ZooKeeper must balance failure detection speed vs false positives.',
 'Performance', 'ZooKeeper', 'ZooKeeper',
 '["False session expirations", "Slow failure detection"]', '["Default timeout not tuned"]', '["ZooKeeper", "HBase"]',
 'Too short: GC pauses cause false expiry. Too long: actual failures go undetected for minutes.',
 'MEDIUM', 'WARNING',
 '["HBase: hbase.zookeeper.session.timeout=90000 (90s, accommodate GC pauses)", "Kafka: zookeeper.session.timeout.ms=18000 (18s, fast detection)", "Set ZK server maxSessionTimeout >= highest client timeout", "Monitor session expiration rate via ZK mntr"]',
 '{"type": "always"}'),

('NIFI-MEMORY-TUNING', 'NiFi JVM and content repo memory',
 'NiFi requires careful memory allocation between JVM heap and content repository.',
 'Performance', 'NiFi', 'NiFi',
 '["NiFi OOM or slow content writes"]', '["Default memory configuration"]', '["NiFi"]',
 'NiFi holds flowfile attributes in heap and content on disk. Wrong sizing starves either.',
 'MEDIUM', 'WARNING',
 '["Set NiFi heap to 4-16GB (-Xms4g -Xmx4g)", "Leave remaining RAM for OS page cache (NiFi content repo is disk-based)", "Set nifi.queue.swap.threshold=20000 to control swap-to-disk behavior", "Monitor heap usage via NiFi System Diagnostics"]',
 '{"type": "always"}'),

('KUDU-HISTORY-MAX-AGE', 'Kudu MVCC history max age',
 'History max age controls how long old row versions are retained for MVCC.',
 'Performance', 'Kudu', 'Kudu',
 '["Excessive storage from old versions"]', '["Default history too long"]', '["Kudu"]',
 'Long history retention stores every version of every updated row, consuming significant storage.',
 'LOW', 'INFO',
 '["Set --tablet_history_max_age_sec=900 (15 minutes) for most workloads", "Increase for slowly-consumed change-tracking workloads", "Shorter = less storage but limits time-travel queries", "Default 900s is appropriate for most OLAP workloads"]',
 '{"type": "always"}'),

('IMPALA-DATA-CACHE', 'Impala local data cache',
 'Impala data cache stores remote HDFS data on local SSDs, reducing read latency for repeated queries.',
 'Performance', 'Impala', 'Impala',
 '["Repeated remote reads"]', '["Data cache not enabled"]', '["Impala"]',
 'Without cache, every query re-reads from HDFS — expensive over network for remote DataNodes.',
 'LOW', 'INFO',
 '["Set --data_cache_dir=/path/to/ssd/impala-cache:SIZE (e.g., :100GB)", "Use SSD storage for cache directory", "Monitor cache hit rate in query profiles", "Most beneficial for repeated queries on the same data"]',
 '{"type": "always"}'),

('NET-BANDWIDTH-INTERRACK', 'Inter-rack network bandwidth',
 'Insufficient bandwidth between racks causes replication and shuffle bottlenecks.',
 'Architecture', 'Network', 'Network',
 '["Replication slowness", "Shuffle bottleneck"]', '["Underprovisioned inter-rack links"]', '["Servers"]',
 'HDFS replication and MapReduce shuffle generate significant cross-rack traffic.',
 'MEDIUM', 'WARNING',
 '["Ensure inter-rack bandwidth is at least 10Gbps for clusters >20 nodes", "Monitor switch port utilization during peak hours", "Consider 40/100Gbps spine for large clusters", "Use rack-aware scheduling to minimize cross-rack traffic"]',
 '{"type": "always"}'),

('SEC-HDFS-ACL', 'HDFS ACL enforcement',
 'HDFS POSIX ACLs provide fine-grained access control beyond basic owner/group/other permissions.',
 'Security', 'Authorization', 'HDFS',
 '["Overly permissive file access"]', '["Only basic POSIX permissions"]', '["HDFS", "Data"]',
 'Without ACLs, granting access to a third group requires making files world-readable.',
 'MEDIUM', 'WARNING',
 '["Enable ACLs: dfs.namenode.acls.enabled=true", "Use setfacl for fine-grained access: hdfs dfs -setfacl -m group:analysts:r-x /data", "Audit ACLs on sensitive directories periodically", "Prefer Ranger policies for centralized management over HDFS ACLs"]',
 '{"type": "always"}'),

('SEC-AUDIT-LOG-REVIEW', 'Regular security audit log review',
 'Audit logs are useless if nobody reviews them. Regular review detects unauthorized access attempts.',
 'Security', 'Auditing', 'Ranger',
 '["Unauthorized access undetected"]', '["Audit logs collected but never reviewed"]', '["Data"]',
 'Attackers succeed when their actions go unreviewed in logs.',
 'HIGH', 'WARNING',
 '["Schedule weekly audit log review for denied access attempts", "Automate: alert on >10 denied accesses from same user in 1 hour", "Review privileged account activity monthly", "Look for: unusual access times, bulk data downloads, access to sensitive classifications"]',
 '{"type": "always"}'),

('HBASE-BUCKET-CACHE', 'HBase BucketCache for off-heap caching',
 'BucketCache enables off-heap block caching, reducing GC pressure for read-heavy workloads.',
 'Performance', 'HBase', 'HBase',
 '["GC pauses from large on-heap cache"]', '["All caching on-heap"]', '["HBase"]',
 'On-heap block cache above 8-10GB causes long G1GC mixed collections.',
 'LOW', 'INFO',
 '["Enable BucketCache: hbase.bucketcache.ioengine=offheap", "Set hbase.bucketcache.size=8192 (8GB off-heap)", "Keep L1 on-heap cache small for index and bloom blocks", "Monitor BucketCache hit rate and eviction rate"]',
 '{"type": "always"}'),

('IMPALA-CODEGEN', 'Impala code generation',
 'Runtime code generation (codegen) JIT-compiles query fragments for 5-10x faster execution.',
 'Performance', 'Impala', 'Impala',
 '["Slow query execution"]', '["Codegen disabled"]', '["Impala"]',
 'Without codegen, Impala interprets every row operation — much slower than generated machine code.',
 'LOW', 'INFO',
 '["Codegen is enabled by default — verify with: SET DISABLE_CODEGEN=false", "Codegen benefits most: hash joins, aggregations, predicates on large tables", "Monitor codegen compilation time in query profiles", "Disable only for debugging: SET DISABLE_CODEGEN=true"]',
 '{"type": "always"}');
