-- V11: Deep practices — compliance frameworks, sizing formulas, workload patterns,
-- cloud integration, performance anti-patterns, logging, operational procedures,
-- service-specific deep tuning, and security hardening.

INSERT INTO recommendation_rules (code, title, description, category, subcategory, component, threat, vulnerability, asset, impact, default_likelihood, default_severity, recommendations_text, condition) VALUES

-- ============================================================
-- SIZING FORMULAS & CAPACITY CALCULATIONS
-- ============================================================

('SIZING-NN-HEAP', 'NameNode heap sizing formula',
 'NameNode heap must be calculated from actual file/block count: ~150 bytes per block + overhead.',
 'Performance', 'HDFS', 'HDFS',
 '["NameNode OOM", "Slow restarts"]', '["Heap not calculated from actual data"]', '["HDFS"]',
 'Under-sized heap causes GC storms and eventual OOM. Over-sized wastes memory and increases GC pause risk.',
 'HIGH', 'CRITICAL',
 '["Formula: heap_GB = (num_blocks * 150 bytes * 2) / 1GB + 4GB overhead", "For 100M blocks: ~34GB heap", "Monitor actual usage: JMX MemHeapUsedM vs MemHeapMaxM", "Plan for 50% headroom above current usage for growth", "Recalculate after major data loads or cluster expansion"]',
 '{"type": "always"}'),

('SIZING-YARN-NM', 'YARN NodeManager memory formula',
 'NM allocatable memory must account for OS, DataNode, and other colocated services.',
 'Performance', 'Yarn', 'Yarn',
 '["OOM kills", "System instability"]', '["NM memory not properly calculated"]', '["Yarn", "Servers"]',
 'Over-allocation causes swapping; under-allocation wastes available capacity.',
 'HIGH', 'WARNING',
 '["Formula: NM_memory = total_RAM - OS_reserve(4GB) - DN_heap(4GB) - NM_heap(2GB) - other_services", "Example 128GB node: 128 - 4 - 4 - 2 = 118GB for containers", "With HBase RS: subtract RS heap (24GB) → 94GB", "Set yarn.nodemanager.resource.memory-mb accordingly"]',
 '{"type": "always"}'),

('SIZING-CONTAINER', 'YARN container size calculation',
 'Container sizes should be based on actual workload requirements and node capacity.',
 'Performance', 'Yarn', 'Yarn',
 '["Wasted resources or OOM"]', '["Arbitrary container sizes"]', '["Yarn"]',
 'Standard container sizes prevent fragmentation and simplify capacity planning.',
 'MEDIUM', 'WARNING',
 '["Define standard container sizes: Small=2GB/1vcore, Medium=4GB/2vcores, Large=8GB/4vcores", "Set yarn.scheduler.minimum-allocation-mb to smallest standard size", "Avoid odd sizes that cause memory fragmentation", "Total containers per node = NM_memory / container_size"]',
 '{"type": "always"}'),

('SIZING-HBASE-RS-HEAP', 'HBase RegionServer heap formula',
 'RegionServer heap must balance memstore, block cache, and overhead.',
 'Performance', 'HBase', 'HBase',
 '["RS OOM or excessive GC"]', '["Heap not sized for workload"]', '["HBase"]',
 'Heap sizing is the #1 HBase tuning priority.',
 'HIGH', 'WARNING',
 '["Formula: heap = memstore(40%) + blockcache(40%) + overhead(20%)", "For 24GB heap: memstore=9.6GB, blockcache=9.6GB, overhead=4.8GB", "Never exceed 31GB with CMS GC (CompressedOops limit)", "With G1GC: up to 64GB is safe with -XX:MaxGCPauseMillis=100"]',
 '{"type": "always"}'),

('SIZING-KAFKA-PARTITION', 'Kafka partition count formula',
 'Partition count must be calculated from throughput requirements and consumer parallelism.',
 'Performance', 'Kafka', 'Kafka',
 '["Insufficient parallelism or excessive overhead"]', '["Arbitrary partition count"]', '["Kafka"]',
 'Too few partitions limit throughput; too many increase metadata overhead and rebalance time.',
 'MEDIUM', 'WARNING',
 '["Formula: partitions = max(target_throughput / per_partition_throughput, consumer_count)", "Per-partition throughput: ~10MB/s producer, ~30MB/s consumer (typical)", "For 100MB/s target: min 10 partitions, but match consumer count", "Total partitions per broker should be <4000"]',
 '{"type": "always"}'),

-- ============================================================
-- PERFORMANCE ANTI-PATTERNS (QUERY LEVEL)
-- ============================================================

('AP-CARTESIAN-JOIN', 'Cartesian join detection',
 'Cartesian (cross) joins produce N*M rows and can exhaust cluster resources.',
 'Performance', 'Query', 'Hive',
 '["Cluster resource exhaustion", "Query never completes"]', '["Missing join condition"]', '["Hive", "Impala", "Spark"]',
 'A cartesian join between two 1M-row tables produces 1 trillion rows — instant cluster kill.',
 'HIGH', 'CRITICAL',
 '["Set hive.strict.checks.cartesian.product=true to block cartesian joins", "Review slow queries for missing ON/WHERE clauses", "Impala: set DISABLE_UNSAFE_SPILLS=true to fail instead of spill", "Educate users on proper join syntax"]',
 '{"type": "always"}'),

('AP-SELECT-STAR', 'Unbounded SELECT * detection',
 'SELECT * FROM large_table without LIMIT or WHERE scans entire table and returns all columns.',
 'Performance', 'Query', 'Hive',
 '["HS2/Impala OOM", "Network saturation"]', '["No query guardrails"]', '["Hive", "Impala"]',
 'Returning 100M rows to a JDBC client crashes the client and wastes cluster I/O.',
 'MEDIUM', 'WARNING',
 '["Set hive.limit.optimize.enable=true", "Set hive.fetch.task.conversion=more for small queries", "Impala: set RESULT_SET_MAX_SIZE to limit result set bytes", "Educate users: always use WHERE, LIMIT, and specific columns"]',
 '{"type": "always"}'),

('AP-FULL-PARTITION-SCAN', 'Full partition scan prevention',
 'Queries without partition pruning predicates scan all partitions — extremely expensive.',
 'Performance', 'Query', 'Hive',
 '["Full table scan of partitioned table"]', '["Missing partition filter"]', '["Hive", "HDFS"]',
 'A daily-partitioned table with 3 years of data has 1095 partitions — scanning all is wasteful.',
 'MEDIUM', 'WARNING',
 '["Set hive.strict.checks.no.partition.filter=true to require partition filter", "Set hive.mapred.mode=strict for similar enforcement", "Monitor queries scanning >100 partitions", "Add partition column to all WHERE clauses"]',
 '{"type": "always"}'),

('AP-DATA-SKEW-JOIN', 'Data skew in join operations',
 'Skewed join keys cause a few reducers to process orders of magnitude more data than others.',
 'Performance', 'Query', 'Hive',
 '["Job stuck on single reducer"]', '["Skewed join keys (nulls, popular values)"]', '["Hive", "Spark"]',
 'One reducer processing 1B rows while 999 others finish in seconds — total waste.',
 'MEDIUM', 'WARNING',
 '["Hive: set hive.optimize.skewjoin=true with hive.skewjoin.key=100000", "Spark: enable AQE skew join: spark.sql.adaptive.skewJoin.enabled=true", "Filter NULL keys before join or handle separately", "Salt skewed keys: add random prefix, join on both, aggregate twice"]',
 '{"type": "always"}'),

('AP-MISSING-PREDICATE-PUSHDOWN', 'Predicate pushdown not applied',
 'Predicates should be pushed down to storage layer to minimize data scanned.',
 'Performance', 'Query', 'Hive',
 '["Excessive data scanned"]', '["Predicates evaluated after full scan"]', '["Hive", "Impala"]',
 'Without pushdown, the entire table is read from disk before filters are applied.',
 'LOW', 'WARNING',
 '["Use ORC/Parquet for predicate pushdown support (not text/CSV)", "Verify pushdown in EXPLAIN plan: look for FilterPredicate in scan operators", "Impala: check runtime filters in query profile", "Ensure column statistics exist for effective pushdown"]',
 '{"type": "always"}'),

-- ============================================================
-- SECURITY HARDENING (DEEP)
-- ============================================================

('SEC-TLS-VERSION', 'TLS version enforcement',
 'All services should enforce TLS 1.2+ and disable older vulnerable versions.',
 'Security', 'Encryption', 'Platform',
 '["Protocol downgrade attacks"]', '["TLS 1.0/1.1 still enabled"]', '["Servers"]',
 'TLS 1.0/1.1 have known vulnerabilities (BEAST, POODLE). PCI-DSS requires TLS 1.2+.',
 'HIGH', 'CRITICAL',
 '["Set ssl.protocol=TLSv1.2 in all service SSL configs", "JVM: -Djdk.tls.client.protocols=TLSv1.2 -Dhttps.protocols=TLSv1.2", "Disable SSLv3, TLSv1, TLSv1.1 in all keystores", "Verify: openssl s_client -connect host:port -tls1_2"]',
 '{"type": "always"}'),

('SEC-CIPHER-SUITES', 'Strong cipher suite enforcement',
 'Weak cipher suites (DES, RC4, export ciphers) must be disabled on all HTTPS/TLS endpoints.',
 'Security', 'Encryption', 'Platform',
 '["Cipher downgrade attacks"]', '["Weak ciphers allowed"]', '["Servers"]',
 'Weak ciphers can be broken in real-time, making encryption meaningless.',
 'HIGH', 'CRITICAL',
 '["Configure ssl.cipher.suites to allow only strong ciphers", "Recommended: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256", "Disable: DES, 3DES, RC4, NULL, EXPORT, anon ciphers", "Test: nmap --script ssl-enum-ciphers -p port host"]',
 '{"type": "always"}'),

('SEC-JAVA-DNS-CACHE', 'Java DNS cache TTL',
 'Default Java DNS cache is infinite, causing stale DNS resolution after IP changes.',
 'Security', 'Network', 'Platform',
 '["Connection failures after DNS changes"]', '["Infinite DNS cache in JVM"]', '["Servers"]',
 'After IP change (e.g., cloud instance replacement), services still connect to old IP indefinitely.',
 'MEDIUM', 'WARNING',
 '["Set networkaddress.cache.ttl=60 in $JAVA_HOME/lib/security/java.security", "Or via JVM flag: -Dsun.net.inetaddr.ttl=60", "Set negative cache: networkaddress.cache.negative.ttl=10", "Critical for cloud deployments where IPs change frequently"]',
 '{"type": "always"}'),

('SEC-UMASK-HDFS', 'HDFS default umask',
 'Default umask controls permissions of newly created files. Must balance security with usability.',
 'Security', 'Authorization', 'HDFS',
 '["Overly permissive new files"]', '["Default umask too open"]', '["HDFS", "Data"]',
 'Default umask 022 creates world-readable files. For sensitive data, this is too permissive.',
 'MEDIUM', 'WARNING',
 '["Set fs.permissions.umask-mode=027 in core-site.xml (owner=rwx, group=r-x, other=---)", "For highly sensitive clusters: 077 (only owner can access)", "Verify: hdfs dfs -touchz /tmp/test && hdfs dfs -ls /tmp/test", "Combine with Ranger policies for fine-grained control"]',
 '{"type": "always"}'),

('SEC-SUPERUSER-PROXY', 'Hadoop superuser proxy configuration',
 'Superuser proxy allows services (Oozie, Hue, Knox) to act on behalf of users. Must be restricted.',
 'Security', 'Authorization', 'Platform',
 '["Privilege escalation via proxy"]', '["Unrestricted superuser proxy"]', '["Servers", "Data"]',
 'Unrestricted proxy allows any service to impersonate any user, bypassing all access controls.',
 'HIGH', 'CRITICAL',
 '["Restrict proxy users in core-site.xml: hadoop.proxyuser.{svc}.hosts=specific_host", "Restrict groups: hadoop.proxyuser.{svc}.groups=specific_groups", "Never use wildcard (*) for hosts or groups in production", "Audit proxy usage in Ranger audit logs"]',
 '{"type": "always"}'),

('SEC-BLOCK-TOKENS', 'HDFS block access tokens',
 'Block access tokens prevent unauthorized direct access to DataNode data blocks.',
 'Security', 'Data Protection', 'HDFS',
 '["Direct data block access bypass"]', '["Block tokens disabled"]', '["HDFS", "Data"]',
 'Without block tokens, anyone with network access to DataNode ports can read raw blocks.',
 'MEDIUM', 'CRITICAL',
 '["Set dfs.block.access.token.enable=true (requires Kerberos)", "Tokens are automatically managed when security is enabled", "Verify: access to DataNode port without token should fail", "Block tokens expire with configurable lifetime"]',
 '{"type": "always"}'),

-- ============================================================
-- LOGGING & OBSERVABILITY
-- ============================================================

('LOG-STRUCTURED', 'Structured logging format',
 'JSON structured logging enables efficient parsing, searching, and correlation across services.',
 'Operations', 'Monitoring', 'Platform',
 '["Unparseable logs", "Slow log search"]', '["Unstructured text logs"]', '["Servers"]',
 'Text logs require regex parsing. Structured logs enable instant field-based queries in ELK/Splunk.',
 'LOW', 'INFO',
 '["Configure log4j JSONLayout for services where supported", "Include standard fields: timestamp, level, service, host, thread, message", "Add correlation ID for cross-service tracing", "Forward structured logs to centralized log platform"]',
 '{"type": "always"}'),

('LOG-LEVELS', 'Service log level configuration',
 'Production log levels should balance detail with volume. DEBUG in production fills disks.',
 'Operations', 'Monitoring', 'Platform',
 '["Disk full from verbose logs", "Missing critical information"]', '["Wrong log level in production"]', '["Servers"]',
 'DEBUG/TRACE creates GB/hour of logs. ERROR-only misses important WARNING context.',
 'MEDIUM', 'WARNING',
 '["Set root logger to INFO for production", "Set WARN for noisy frameworks (Jetty, Jersey, Zookeeper client)", "Set DEBUG only for actively investigated components", "Implement dynamic log level change without restart (JMX or Ambari)"]',
 '{"type": "always"}'),

('LOG-CENTRALIZATION', 'Centralized log management',
 'All service logs should be collected in a central platform for search, correlation, and retention.',
 'Operations', 'Monitoring', 'Platform',
 '["Cannot correlate cross-service issues"]', '["Logs only on local disk"]', '["Servers"]',
 'Searching logs across 50 nodes via SSH is impractical during incidents.',
 'MEDIUM', 'WARNING',
 '["Deploy ELK (Elasticsearch/Logstash/Kibana) or Splunk", "Use Filebeat/Fluentd as log shippers on each node", "Configure retention per log type (security=1yr, debug=30days)", "Create dashboards for common error patterns"]',
 '{"type": "always"}'),

-- ============================================================
-- OPERATIONAL PROCEDURES
-- ============================================================

('PROC-DECOMMISSION', 'Node decommission procedure',
 'A documented, tested procedure for safely removing nodes without data loss.',
 'Operations', 'Process', 'Platform',
 '["Data loss during decommission"]', '["No procedure"]', '["HDFS", "Servers"]',
 'Removing a DataNode without decommission causes under-replication. Removing an NM kills running containers.',
 'MEDIUM', 'WARNING',
 '["HDFS: add host to dfs.hosts.exclude, run hdfs dfsadmin -refreshNodes, wait for decommission to complete", "YARN: graceful decommission via yarn rmadmin -refreshNodes", "HBase: graceful_stop.sh to move regions first", "Never force-remove nodes with active data"]',
 '{"type": "always"}'),

('PROC-RACK-EXPANSION', 'Rack expansion procedure',
 'Adding new racks requires updating topology, rebalancing, and rack-awareness configuration.',
 'Operations', 'Process', 'Platform',
 '["Unbalanced data after expansion"]', '["No expansion procedure"]', '["HDFS", "Servers"]',
 'New racks start empty. Without rebalancing, they serve no reads and only handle new writes.',
 'LOW', 'WARNING',
 '["Update topology script with new rack mappings", "Run HDFS balancer after adding new rack", "Verify rack awareness: hdfs dfsadmin -printTopology", "Update Kafka broker.rack for new Kafka brokers"]',
 '{"type": "always"}'),

('PROC-UPGRADE-PLAN', 'Cluster upgrade procedure',
 'Major version upgrades require documented plan with rollback strategy and compatibility testing.',
 'Operations', 'Process', 'Platform',
 '["Failed upgrade with no rollback"]', '["No upgrade plan"]', '["Servers"]',
 'A failed upgrade without rollback plan can leave the cluster in an inconsistent state for days.',
 'HIGH', 'CRITICAL',
 '["Document upgrade order: ZK → HDFS → YARN → HBase → Hive → Impala → Spark", "Test upgrade in staging with representative data", "Create NameNode/HBase snapshots before upgrade as rollback point", "Plan for rolling upgrade where supported to minimize downtime"]',
 '{"type": "always"}'),

('PROC-EMERGENCY-ACCESS', 'Emergency break-glass access',
 'Emergency access procedure for when primary authentication (Kerberos/LDAP) is down.',
 'Operations', 'Security', 'Platform',
 '["Locked out during emergency"]', '["No break-glass procedure"]', '["Servers"]',
 'If KDC is down and all access requires Kerberos, nobody can fix the KDC.',
 'HIGH', 'CRITICAL',
 '["Maintain local root/admin accounts on critical hosts (KDC, NameNode, Ambari)", "Store break-glass credentials in sealed envelope or hardware vault", "Document break-glass procedure with step-by-step instructions", "Test annually: verify break-glass access works"]',
 '{"type": "always"}'),

-- ============================================================
-- WORKLOAD-SPECIFIC PATTERNS
-- ============================================================

('WL-ETL-CHECKPOINT', 'ETL checkpoint and restart capability',
 'Long-running ETL jobs should support checkpointing to avoid re-processing from scratch on failure.',
 'Operations', 'Pipeline', 'Platform',
 '["Hours of wasted computation on failure"]', '["No checkpointing"]', '["Spark", "Hive"]',
 'A 6-hour Spark job failing at 5h50min with no checkpoint means re-running the entire 6 hours.',
 'MEDIUM', 'WARNING',
 '["Spark: use spark.checkpoint.dir for reliable checkpointing", "Implement staged ETL: raw→staging→curated with intermediate persistence", "Use Oozie/Airflow to break long jobs into restartable stages", "Store watermarks/offsets in external state store (HBase, RDBMS)"]',
 '{"type": "always"}'),

('WL-STREAMING-EXACTLY-ONCE', 'Streaming exactly-once processing verification',
 'End-to-end exactly-once requires coordinating Kafka offsets with sink commits.',
 'Operations', 'Pipeline', 'Kafka',
 '["Duplicate or lost records in streaming"]', '["At-least-once default"]', '["Kafka", "Spark"]',
 'Most streaming frameworks default to at-least-once. Exactly-once requires explicit configuration.',
 'HIGH', 'WARNING',
 '["Kafka Streams: processing.guarantee=exactly_once_v2 (Kafka 2.5+)", "Spark Structured Streaming: use foreachBatch with idempotent sink", "Flink: enable checkpointing with exactly-once semantics", "Verify: inject known count, validate exact count at sink"]',
 '{"type": "always"}'),

('WL-ML-PIPELINE', 'ML pipeline resource isolation',
 'ML training jobs are resource-intensive and should be isolated from production workloads.',
 'Performance', 'Yarn', 'Yarn',
 '["ML jobs starving production"]', '["No ML resource isolation"]', '["Yarn", "Spark"]',
 'A single ML training job requesting 100 GPUs or 2TB RAM can block all production ETL.',
 'MEDIUM', 'WARNING',
 '["Create dedicated YARN queue for ML workloads with hard capacity limit", "Use node labels to restrict ML to GPU/high-memory nodes", "Set per-application resource limits for ML jobs", "Schedule intensive training during off-peak hours"]',
 '{"type": "always"}'),

('WL-BATCH-WINDOW', 'Batch processing window management',
 'Batch jobs should complete within defined windows to not overlap with next cycle.',
 'Operations', 'Pipeline', 'Platform',
 '["Cascading delays from batch overrun"]', '["No batch window management"]', '["Yarn"]',
 'A nightly batch overrunning into business hours competes with interactive queries.',
 'MEDIUM', 'WARNING',
 '["Define batch windows: e.g., nightly=00:00-06:00, weekly=Saturday", "Monitor batch completion time trend — alert if approaching window end", "Implement batch timeout: kill if exceeding window + 1h buffer", "Optimize long-running jobs before they breach the window"]',
 '{"type": "always"}'),

-- ============================================================
-- CLOUD & HYBRID INTEGRATION
-- ============================================================

('CLOUD-S3-CONFIG', 'S3/ADLS/GCS connector configuration',
 'Cloud storage connectors must be properly tuned for performance and reliability.',
 'Performance', 'Cloud', 'HDFS',
 '["Slow cloud reads/writes", "Connection timeout"]', '["Default connector settings"]', '["HDFS"]',
 'Default S3A settings cause slow uploads, timeout failures, and excessive API calls.',
 'MEDIUM', 'WARNING',
 '["Set fs.s3a.connection.maximum=200 (default 15 is too low)", "Set fs.s3a.threads.max=64 for parallel uploads", "Enable fs.s3a.fast.upload=true for multipart upload", "Set fs.s3a.multipart.size=256M for large files", "Set fs.s3a.connection.timeout=200000 for reliability"]',
 '{"type": "always"}'),

('CLOUD-IAM-INTEGRATION', 'Cloud IAM integration',
 'Cloud storage access should use IAM roles, not static credentials embedded in configuration.',
 'Security', 'Cloud', 'Platform',
 '["Credential exposure"]', '["Static cloud credentials in configs"]', '["Data"]',
 'Static access keys in config files can be leaked through config drift reports or SCM.',
 'HIGH', 'CRITICAL',
 '["Use instance profiles/managed identities instead of access keys", "AWS: use IAM roles for EC2 instances, never fs.s3a.access.key in config", "Azure: use managed identity with fs.azure.account.auth.type=OAuth", "Rotate any existing static credentials immediately"]',
 '{"type": "always"}'),

-- ============================================================
-- SERVICE-SPECIFIC DEEP TUNING
-- ============================================================

('HIVE-TEZ-CONTAINER', 'Hive Tez container sizing',
 'Tez container size determines per-task memory for Hive queries. Too small causes spill; too large wastes.',
 'Performance', 'Hive', 'Hive',
 '["Query OOM or excessive spill"]', '["Tez container not tuned"]', '["Hive", "Yarn"]',
 'Default Tez container inherits YARN minimum which is often too small for complex queries.',
 'MEDIUM', 'WARNING',
 '["Set hive.tez.container.size=4096 (4GB) for most workloads", "Set hive.tez.java.opts=-Xmx3276m (80% of container)", "Match to YARN minimum allocation increment for efficient packing", "Increase for complex joins or large GROUP BY operations"]',
 '{"type": "always"}'),

('HIVE-FETCH-CONVERSION', 'Hive fetch task conversion',
 'Simple queries should use fetch task to avoid launching MapReduce/Tez jobs entirely.',
 'Performance', 'Hive', 'Hive',
 '["Unnecessary job launch for simple queries"]', '["Fetch conversion disabled or minimal"]', '["Hive"]',
 'SELECT * FROM table LIMIT 10 should not launch a Tez DAG — it should read directly.',
 'LOW', 'INFO',
 '["Set hive.fetch.task.conversion=more (default)", "Set hive.fetch.task.conversion.threshold=1073741824 (1GB)", "This enables instant results for: SELECT col, LIMIT, small table scans", "Monitor: queries running as fetch tasks vs full jobs"]',
 '{"type": "always"}'),

('HBASE-PREFETCH', 'HBase block prefetch on open',
 'Prefetching blocks when a region opens reduces cold-start read latency.',
 'Performance', 'HBase', 'HBase',
 '["High latency after region move"]', '["No prefetch on open"]', '["HBase"]',
 'After region reassignment, first reads hit disk instead of cache — high latency for seconds to minutes.',
 'LOW', 'INFO',
 '["Set hfile.block.cache.prefetch=true for read-heavy tables", "Set per column family: alter table, {NAME=>cf, PREFETCH_BLOCKS_ON_OPEN=>true}", "Increases region open time but eliminates cold-start penalty", "Best for tables with predictable hot regions"]',
 '{"type": "always"}'),

('KAFKA-PRODUCER-TUNING', 'Kafka producer performance tuning',
 'Producer batch size, linger, and buffer settings dramatically affect throughput.',
 'Performance', 'Kafka', 'Kafka',
 '["Low producer throughput"]', '["Default producer settings"]', '["Kafka"]',
 'Default settings optimize for latency. Production often needs throughput optimization.',
 'LOW', 'WARNING',
 '["Set batch.size=65536 (64KB, up from default 16KB) for throughput", "Set linger.ms=5-50 to batch more records per request", "Set buffer.memory=67108864 (64MB) for burst handling", "Set compression.type=lz4 for best throughput/compression tradeoff", "Verify with: kafka-producer-perf-test.sh"]',
 '{"type": "always"}'),

('KAFKA-CONSUMER-TUNING', 'Kafka consumer performance tuning',
 'Consumer fetch size and poll configuration affect throughput and rebalance stability.',
 'Performance', 'Kafka', 'Kafka',
 '["Low consumer throughput", "Frequent rebalances"]', '["Default consumer settings"]', '["Kafka"]',
 'Default max.poll.records=500 is too low for high-throughput consumers.',
 'LOW', 'WARNING',
 '["Set max.poll.records=1000-5000 based on processing speed", "Set max.poll.interval.ms=300000 (5min) to avoid rebalance during slow batches", "Set fetch.min.bytes=1048576 (1MB) for throughput", "Set session.timeout.ms=45000 with heartbeat.interval.ms=15000"]',
 '{"type": "always"}'),

('IMPALA-THREAD-POOL', 'Impala daemon thread pool',
 'Impala daemon thread pool controls query parallelism. Must match expected concurrent query count.',
 'Performance', 'Impala', 'Impala',
 '["Query queuing from thread exhaustion"]', '["Default thread pool"]', '["Impala"]',
 'When all threads are busy, new queries queue, adding unexpected latency.',
 'LOW', 'WARNING',
 '["Set --fe_service_threads=128 for high-concurrency workloads", "Set --be_num_query_exec_threads based on CPU cores", "Monitor active/queued query counts in Impala web UI", "Scale thread pool with expected concurrent queries"]',
 '{"type": "always"}'),

('SPARK-BROADCAST-THRESHOLD', 'Spark broadcast join threshold',
 'Tables below the broadcast threshold are broadcast to all executors, avoiding expensive shuffle joins.',
 'Performance', 'Spark', 'Spark',
 '["Unnecessary shuffle for small table joins"]', '["Threshold too low"]', '["Spark"]',
 'Default 10MB threshold misses many dimension tables that fit in memory.',
 'LOW', 'INFO',
 '["Set spark.sql.autoBroadcastJoinThreshold=52428800 (50MB) for most clusters", "For large executor memory, increase to 100-200MB", "Disable with -1 if broadcast causes driver OOM", "Verify in Spark UI: BroadcastHashJoin vs SortMergeJoin"]',
 '{"type": "always"}'),

('SPARK-PARTITION-OVERWRITE', 'Spark dynamic partition overwrite',
 'Dynamic partition overwrite replaces only touched partitions, not the entire table.',
 'Performance', 'Spark', 'Spark',
 '["Accidental data deletion", "Full table rewrite for single partition"]', '["Static partition overwrite mode"]', '["Spark"]',
 'Default INSERT OVERWRITE replaces ALL partitions, even those not in the new data.',
 'HIGH', 'WARNING',
 '["Set spark.sql.sources.partitionOverwriteMode=dynamic", "This replaces only partitions present in the output DataFrame", "Verify behavior with test data before production use", "Critical for incremental partition updates"]',
 '{"type": "always"}'),

-- ============================================================
-- COMPLIANCE FRAMEWORKS
-- ============================================================

('COMPLY-AUDIT-TRAIL', 'Compliance audit trail completeness',
 'Regulatory frameworks (SOX, HIPAA, PCI) require complete audit trails for data access and changes.',
 'Governance', 'Compliance', 'Ranger',
 '["Regulatory violation", "Failed audit"]', '["Incomplete audit trail"]', '["Data"]',
 'An incomplete audit trail fails regulatory audits and prevents forensic investigation.',
 'HIGH', 'CRITICAL',
 '["Ensure Ranger audit captures all access to regulated data (not just denies)", "Configure audit for: HDFS, Hive, HBase, Kafka access", "Retain audit logs per regulatory requirement (SOX=7yr, HIPAA=6yr, PCI=1yr)", "Regularly verify audit completeness: sample checks against known access"]',
 '{"type": "always"}'),

('COMPLY-ENCRYPTION-AT-REST', 'Encryption at rest for regulated data',
 'Regulated data (PCI, HIPAA, GDPR) must be encrypted at rest using approved algorithms.',
 'Governance', 'Compliance', 'HDFS',
 '["Compliance violation", "Data breach liability"]', '["Unencrypted regulated data"]', '["HDFS", "Data"]',
 'Unencrypted regulated data on disk is a compliance violation regardless of network encryption.',
 'HIGH', 'CRITICAL',
 '["Create HDFS encryption zones for all directories containing regulated data", "Use AES-256 encryption via Ranger KMS", "Verify: hdfs crypto -listZones should show all regulated paths", "Extend to HBase: enable HFile encryption for regulated column families"]',
 '{"type": "always"}'),

('COMPLY-ACCESS-REVIEW', 'Periodic access review',
 'Access rights must be reviewed periodically to remove stale permissions.',
 'Governance', 'Compliance', 'Ranger',
 '["Excessive access accumulation"]', '["No periodic review"]', '["Data"]',
 'Over time, users accumulate permissions from role changes. Without review, ex-team members retain access.',
 'HIGH', 'WARNING',
 '["Schedule quarterly access review for all regulated data", "Generate access report per dataset from Ranger policies", "Require manager approval for continued access", "Remove access for users who have not accessed data in 90 days"]',
 '{"type": "always"}'),

('COMPLY-DATA-MASKING-VERIFY', 'Data masking verification',
 'Verify that masking policies effectively protect sensitive data and cannot be bypassed.',
 'Governance', 'Compliance', 'Ranger',
 '["Masking bypass exposing sensitive data"]', '["Masking not verified"]', '["Data"]',
 'Masking rules can have gaps — a view or derived table might expose unmasked data.',
 'MEDIUM', 'WARNING',
 '["Test masking as each user role: verify masked data appears correctly", "Check for bypass paths: direct HDFS access, HBase shell, Spark direct read", "Ensure masking applies to all access paths (Hive, Impala, Spark SQL)", "Monitor Ranger audit for masked column access"]',
 '{"type": "always"}'),

-- ============================================================
-- ADVANCED CLUSTER HEALTH
-- ============================================================

('HEALTH-DISK-BALANCE', 'DataNode disk utilization balance',
 'Uneven disk utilization within a DataNode wastes capacity and concentrates I/O.',
 'Performance', 'HDFS', 'HDFS',
 '["Hot disk while others idle"]', '["No intra-node disk balancing"]', '["HDFS"]',
 'HDFS assigns blocks round-robin across disks, but sizes differ. Over time, imbalance grows.',
 'LOW', 'WARNING',
 '["Enable DataNode disk balancer: hdfs diskbalancer -plan <datanode>", "Set dfs.disk.balancer.max.disk.throughput=10485760 (10MB/s)", "Run periodically or when disk utilization variance exceeds 20%", "HDFS 3.x: automatic disk balancing is improved"]',
 '{"type": "always"}'),

('HEALTH-GC-PAUSE-MONITORING', 'GC pause time monitoring',
 'GC pauses above thresholds indicate memory pressure and impending service disruptions.',
 'Performance', 'JVM', 'Platform',
 '["Service timeouts from GC pauses"]', '["GC pauses not monitored"]', '["HBase", "HDFS"]',
 'A 30-second GC pause on HBase RS causes ZK session expiry and region reassignment.',
 'HIGH', 'WARNING',
 '["Alert on GC pause > 5s for any service", "Critical alert on GC pause > 10s for HBase RS and NameNode", "Monitor via JMX: GcTimeMillis and GcCount trends", "GC pause increase trend = impending OOM, investigate immediately"]',
 '{"type": "always"}'),

('HEALTH-THREAD-DEADLOCK', 'Thread deadlock detection',
 'Deadlocked threads cause service hangs without error messages.',
 'Performance', 'JVM', 'Platform',
 '["Service hangs silently"]', '["No deadlock detection"]', '["Servers"]',
 'A deadlocked NameNode or RegionServer appears up but cannot process any requests.',
 'MEDIUM', 'WARNING',
 '["Enable JMX deadlock detection monitoring", "Schedule periodic jstack analysis for critical services", "Monitor thread blocked count via JMX: ThreadsBlocked trend", "Alert when ThreadsBlocked > 10 for any service"]',
 '{"type": "always"}'),

('HEALTH-NETWORK-PARTITION', 'Network partition detection',
 'Split-brain from network partitions can cause data corruption in distributed systems.',
 'Architecture', 'Network', 'Platform',
 '["Split-brain data corruption"]', '["No partition detection"]', '["ZooKeeper", "HBase", "Kafka"]',
 'Network partition without detection leads to multiple leaders and divergent writes.',
 'HIGH', 'CRITICAL',
 '["Monitor network connectivity between all ZK nodes (ping mesh)", "Configure ZK/HBase/Kafka with appropriate session timeouts", "Implement fencing mechanisms (STONITH) for HDFS HA", "Alert on intermittent connectivity: packet loss >0.1% between nodes"]',
 '{"type": "always"}'),

('HEALTH-CLOCK-SKEW', 'Clock skew monitoring',
 'Clock skew between nodes causes Kerberos failures, HBase issues, and log correlation problems.',
 'Architecture', 'OS', 'OS',
 '["Kerberos auth failures", "HBase transaction ordering issues"]', '["Clock drift between nodes"]', '["Servers", "Kerberos"]',
 'Kerberos allows max 5 minutes skew by default. Kudu allows max 500ms.',
 'HIGH', 'CRITICAL',
 '["Monitor clock offset between all nodes (chronyc sources, ntpstat)", "Alert when offset > 1 second between any pair", "Critical alert when offset > 5 minutes (Kerberos will fail)", "Kudu: alert when offset > 200ms"]',
 '{"type": "always"}');
