-- V4: Best-practice recommendation rules for HBase, HDFS (advanced), YARN (advanced), Impala, Kudu.

INSERT INTO recommendation_rules (code, title, description, category, subcategory, component, threat, vulnerability, asset, impact, default_likelihood, default_severity, recommendations_text, condition) VALUES

-- ============================================================
-- HBASE > MEMORY
-- ============================================================

('HBASE-HEAP-SIZE', 'HBase RegionServer heap sizing',
 'RegionServer heap should be between 16GB and 31GB. Below 16GB limits performance; above 31GB causes long GC pauses with CMS. G1GC can handle up to 64GB.',
 'Performance', 'HBase', 'HBase',
 '["Performance degradation", "GC pauses causing RegionServer timeouts"]',
 '["Undersized or oversized JVM heap"]',
 '["HBase", "Data"]',
 'Wrong heap size causes either insufficient cache/memstore capacity or catastrophic GC pauses leading to ZooKeeper session expiry and RegionServer death.',
 'HIGH', 'CRITICAL',
 '["Set RegionServer heap between 16GB-31GB for CMS GC", "If using G1GC, heap can go up to 64GB", "Configure with HBASE_REGIONSERVER_OPTS=-Xms24g -Xmx24g", "Monitor GC pause times and adjust accordingly"]',
 '{"type": "always"}'),

('HBASE-BLOCKCACHE', 'HBase block cache configuration',
 'Block cache should be 40% of heap (default). Combined with memstore, should not exceed 80% of heap.',
 'Performance', 'HBase', 'HBase',
 '["Performance degradation", "Read latency increase"]',
 '["Misconfigured block cache ratio"]',
 '["HBase"]',
 'Too small block cache increases disk reads; too large starves memstore and causes premature flushes.',
 'MEDIUM', 'WARNING',
 '["Set hfile.block.cache.size to 0.4 (40%) in hbase-site.xml", "Ensure hbase.regionserver.global.memstore.size + hfile.block.cache.size <= 0.8", "Consider BucketCache off-heap for read-heavy workloads", "Monitor block cache hit ratio — aim for >85%"]',
 '{"type": "always"}'),

('HBASE-MEMSTORE', 'HBase memstore configuration',
 'Memstore flush size and global limits must be properly configured to avoid RegionServer pauses.',
 'Performance', 'HBase', 'HBase',
 '["Write stalls", "RegionServer pauses"]',
 '["Misconfigured memstore limits"]',
 '["HBase"]',
 'When global memstore hits upper limit, all writes are blocked until flushes complete. This causes cascading delays.',
 'MEDIUM', 'WARNING',
 '["Set hbase.regionserver.global.memstore.size to 0.4 (40% of heap)", "Set hbase.regionserver.global.memstore.size.lower.limit to 0.95", "Set hbase.hregion.memstore.flush.size to 128MB-256MB", "Monitor memstore usage via JMX metrics"]',
 '{"type": "always"}'),

('HBASE-MSLAB', 'HBase MSLAB (MemStore-Local Allocation Buffer)',
 'MSLAB reduces heap fragmentation by pre-allocating memory chunks for memstore. Should be enabled in production.',
 'Performance', 'HBase', 'HBase',
 '["Heap fragmentation", "Long GC pauses"]',
 '["Default MSLAB settings not optimal"]',
 '["HBase"]',
 'Without MSLAB, memstore allocations cause heap fragmentation leading to full GC pauses.',
 'LOW', 'WARNING',
 '["Ensure hbase.hregion.memstore.mslab.enabled=true", "Set hbase.hregion.memstore.mslab.chunksize=2097152 (2MB)", "Set hbase.hregion.memstore.mslab.max.allocation=262144 (256KB)"]',
 '{"type": "metadata_check", "path": "hbase.mslab.enabled", "operator": "equals", "expected": true}'),

('HBASE-GC', 'HBase GC configuration',
 'RegionServers should use G1GC for heaps above 16GB. CMS is acceptable for smaller heaps but prone to long pauses with large heaps.',
 'Performance', 'HBase', 'HBase',
 '["RegionServer unresponsive", "ZooKeeper session expiry"]',
 '["Suboptimal GC algorithm"]',
 '["HBase"]',
 'Long GC pauses (>10s) cause ZooKeeper session timeout and the RegionServer is considered dead, triggering region reassignment.',
 'HIGH', 'CRITICAL',
 '["Use G1GC for heaps >16GB: -XX:+UseG1GC", "Set -XX:MaxGCPauseMillis=100 for G1GC", "Set -XX:+ParallelRefProcEnabled", "Monitor GC logs: enable -Xloggc with -XX:+PrintGCDetails"]',
 '{"type": "always"}'),

-- ============================================================
-- HBASE > COLOCATION
-- ============================================================

('HBASE-COLOC-NN', 'HBase RegionServer colocated with NameNode',
 'RegionServers should NOT run on the same host as NameNode. Both are memory-intensive and compete for resources.',
 'Architecture', 'HBase', 'HBase',
 '["Resource contention", "Cascading failures"]',
 '["Service colocation on shared host"]',
 '["HBase", "HDFS"]',
 'NameNode and RegionServer both require large heaps. Colocation causes memory pressure, GC storms, and correlated failures.',
 'HIGH', 'CRITICAL',
 '["Move RegionServer to a dedicated host", "If not possible, reduce heap sizes and monitor closely", "Never colocate master components on the same host"]',
 '{"type": "list_not_empty", "path": "hbase_metrics.colocation.rs_on_namenode"}'),

('HBASE-COLOC-RM', 'HBase RegionServer colocated with ResourceManager',
 'RegionServers should NOT run on the same host as YARN ResourceManager to avoid resource contention.',
 'Architecture', 'HBase', 'HBase',
 '["Resource contention", "Cascading failures"]',
 '["Service colocation on shared host"]',
 '["HBase", "Yarn"]',
 'ResourceManager and RegionServer compete for CPU and memory, degrading both HBase and YARN performance.',
 'HIGH', 'WARNING',
 '["Move RegionServer or ResourceManager to separate hosts", "Master components (NN, RM, HMaster) should be on dedicated hosts"]',
 '{"type": "list_not_empty", "path": "hbase_metrics.colocation.rs_on_resourcemanager"}'),

('HBASE-DEAD-RS', 'Dead HBase RegionServers',
 'Dead RegionServers cause region unavailability and trigger expensive region reassignment.',
 'Architecture', 'High Availability', 'HBase',
 '["Data unavailability", "Read/write failures"]',
 '["RegionServer process failure", "Network partition"]',
 '["HBase", "Data"]',
 'Dead RegionServers make their hosted regions unavailable. Recovery involves log splitting and region reassignment which can take minutes.',
 'HIGH', 'CRITICAL',
 '["Check RegionServer process status and logs", "Verify network connectivity to ZooKeeper", "Check for disk failures on the host", "Monitor ZooKeeper session timeouts"]',
 '{"type": "threshold_check", "path": "hbase_metrics.hmaster.num_dead_region_servers", "threshold": 0, "direction": "above"}'),

('HBASE-REGION-COUNT', 'HBase region count per RegionServer',
 'Each RegionServer should host 20-200 regions. Over 500 causes excessive overhead from memstore flushes, compactions, and ZK sessions.',
 'Performance', 'HBase', 'HBase',
 '["Performance degradation", "RegionServer instability"]',
 '["Too many regions per server"]',
 '["HBase"]',
 'High region count increases memstore memory, flush frequency, compaction load, and ZK session count. This is the #1 HBase performance problem.',
 'HIGH', 'WARNING',
 '["Merge small regions: hbase shell > merge_region", "Pre-split tables with appropriate split keys", "Increase region max size: hbase.hregion.max.filesize (default 10GB)", "Consider table redesign if region count is organic"]',
 '{"type": "always"}'),

('HBASE-COMPACTION-QUEUE', 'HBase compaction queue backlog',
 'A growing compaction queue indicates that compaction cannot keep up with writes, degrading read performance.',
 'Performance', 'HBase', 'HBase',
 '["Read performance degradation"]',
 '["Write-heavy workload exceeding compaction capacity"]',
 '["HBase"]',
 'Compaction backlog means more store files per region, causing slower reads due to more files to scan.',
 'MEDIUM', 'WARNING',
 '["Increase compaction threads: hbase.regionserver.thread.compaction.large/small", "Schedule major compaction during off-peak hours", "Consider using Stripe compaction for large regions", "Review write patterns and table schema"]',
 '{"type": "always"}'),

('HBASE-RIT', 'HBase regions in transition',
 'Regions stuck in transition indicate cluster instability. Any non-zero RIT count should be investigated.',
 'Architecture', 'HBase', 'HBase',
 '["Data unavailability", "Cluster instability"]',
 '["Region assignment failure", "Master/ZK issues"]',
 '["HBase"]',
 'Stuck RIT means some regions are not being served, causing read/write failures for affected tables.',
 'HIGH', 'CRITICAL',
 '["Check HMaster logs for assignment errors", "Verify ZooKeeper health and connectivity", "Use hbase hbck to diagnose and fix region assignment", "Restart HMaster if RIT persists after ZK verification"]',
 '{"type": "threshold_check", "path": "hbase_metrics.hmaster.rit_count_over_threshold", "threshold": 0, "direction": "above"}'),

('HBASE-SHORT-CIRCUIT', 'HBase short-circuit reads',
 'Short-circuit reads bypass network and read data directly from local disk. Critical for HBase read performance.',
 'Performance', 'HBase', 'HDFS',
 '["Read latency increase"]',
 '["Short-circuit reads not enabled"]',
 '["HBase", "HDFS"]',
 'Without short-circuit reads, every HBase read goes through the DataNode RPC, adding 1-5ms latency per read.',
 'HIGH', 'WARNING',
 '["Set dfs.client.read.shortcircuit=true in hdfs-site.xml", "Set dfs.domain.socket.path to /var/lib/hadoop-hdfs/dn_socket", "Set dfs.client.read.shortcircuit.skip.checksum=false (keep checksums)", "Restart DataNodes and RegionServers after change"]',
 '{"type": "metadata_check", "path": "hdfs.short_circuit_reads", "operator": "equals", "expected": true}'),

-- ============================================================
-- HDFS > ADVANCED BEST PRACTICES
-- ============================================================

('HDFS-SHORT-CIRCUIT', 'HDFS short-circuit local reads',
 'Short-circuit reads allow clients on the same node as a DataNode to read directly from disk, bypassing the DataNode process.',
 'Performance', 'HDFS', 'HDFS',
 '["Read latency increase"]',
 '["Short-circuit reads disabled (default)"]',
 '["HDFS"]',
 'Short-circuit reads reduce read latency by 50-80% for local reads, critical for HBase and Impala.',
 'MEDIUM', 'WARNING',
 '["Set dfs.client.read.shortcircuit=true in hdfs-site.xml", "Configure dfs.domain.socket.path", "Ensure libhadoop.so native library is available"]',
 '{"type": "metadata_check", "path": "hdfs.short_circuit_reads", "operator": "equals", "expected": true}'),

('HDFS-BLOCK-SIZE', 'HDFS block size configuration',
 'Block size should be 128MB or 256MB for most workloads. Smaller blocks waste NameNode memory; larger blocks reduce parallelism.',
 'Performance', 'HDFS', 'HDFS',
 '["NameNode memory waste", "Reduced parallelism"]',
 '["Suboptimal block size for workload"]',
 '["HDFS"]',
 'Each block consumes ~150 bytes of NameNode memory. Small blocks create millions of entries. Too large blocks reduce MapReduce parallelism.',
 'LOW', 'INFO',
 '["Set dfs.blocksize=134217728 (128MB) or 268435456 (256MB)", "Use 256MB for large sequential workloads", "Use 128MB for mixed workloads with MapReduce", "Never use block sizes below 64MB"]',
 '{"type": "always"}'),

('HDFS-REPLICATION', 'HDFS replication factor',
 'Production clusters should use replication factor 3. Lower values risk data loss.',
 'Architecture', 'HDFS', 'HDFS',
 '["Data loss"]',
 '["Insufficient replication"]',
 '["HDFS", "Data"]',
 'With replication < 3, a single disk/node failure can cause data loss if another failure occurs during re-replication.',
 'HIGH', 'CRITICAL',
 '["Set dfs.replication=3 in hdfs-site.xml (default, verify it has not been lowered)", "For critical data, consider replication factor 4-5", "Use erasure coding (HDFS 3.x) for cold data to save space with same durability"]',
 '{"type": "metadata_check", "path": "hdfs.replication_factor", "operator": "equals", "expected": 3}'),

('HDFS-TRASH', 'HDFS trash enabled',
 'Trash provides a safety net against accidental deletion. Critical for production clusters.',
 'Architecture', 'HDFS', 'HDFS',
 '["Accidental data loss"]',
 '["No trash/recycle bin configured"]',
 '["HDFS", "Data"]',
 'Without trash, deleted files are immediately and permanently removed with no recovery option.',
 'MEDIUM', 'WARNING',
 '["Set fs.trash.interval=1440 (24 hours) in core-site.xml", "Set fs.trash.checkpoint.interval=60 (1 hour)", "Educate users about hdfs dfs -expunge to empty trash", "Monitor trash size to avoid filling HDFS"]',
 '{"type": "metadata_check", "path": "hdfs.trash.enabled", "operator": "equals", "expected": true}'),

('HDFS-HANDLER-COUNT', 'HDFS NameNode handler count',
 'NameNode handler count should be tuned based on cluster size. Default (10) is too low for most production clusters.',
 'Performance', 'HDFS', 'HDFS',
 '["RPC queue saturation", "Client timeouts"]',
 '["Default handler count too low for cluster size"]',
 '["HDFS"]',
 'Insufficient handlers cause RPC queue backlog, increasing client latency and potentially causing timeouts.',
 'MEDIUM', 'WARNING',
 '["Set dfs.namenode.handler.count = 20 * ln(num_cluster_nodes) as a starting point", "For 10 nodes: 46, for 50 nodes: 78, for 200 nodes: 106", "Monitor RPC queue time via JMX: RpcQueueTimeAvgTime", "Also tune dfs.namenode.service.handler.count for DataNode RPCs"]',
 '{"type": "always"}'),

('HDFS-RACK-AWARENESS', 'HDFS rack awareness',
 'Rack awareness ensures replicas are spread across racks, protecting against rack-level failures.',
 'Architecture', 'HDFS', 'HDFS',
 '["Data loss from rack failure"]',
 '["All replicas on same rack"]',
 '["HDFS", "Data"]',
 'Without rack awareness, all 3 replicas may be on the same rack. A rack failure (switch/power) loses all copies.',
 'MEDIUM', 'CRITICAL',
 '["Configure net.topology.script.file.name in core-site.xml", "Define rack topology for all DataNodes", "Verify with: hdfs dfsadmin -printTopology", "Ensure at least 2 racks for replication factor 3"]',
 '{"type": "metadata_check", "path": "hdfs.rack_awareness", "operator": "equals", "expected": true}'),

-- ============================================================
-- YARN > ADVANCED BEST PRACTICES
-- ============================================================

('YARN-CONTAINER-MEM', 'YARN container memory configuration',
 'Minimum container memory should be at least 1GB. Maximum should not exceed 80% of node RAM divided by number of containers.',
 'Performance', 'Yarn', 'Yarn',
 '["OOM kills", "Resource waste"]',
 '["Misconfigured container memory limits"]',
 '["Yarn"]',
 'Too small containers cause OOM; too large containers waste resources and reduce parallelism.',
 'MEDIUM', 'WARNING',
 '["Set yarn.scheduler.minimum-allocation-mb=1024 (1GB minimum)", "Set yarn.scheduler.maximum-allocation-mb based on node capacity", "Set yarn.nodemanager.resource.memory-mb = total_RAM * 0.8", "Leave 20% RAM for OS, DataNode, and NodeManager overhead"]',
 '{"type": "always"}'),

('YARN-CONTAINER-VCORES', 'YARN vcore allocation',
 'Vcores should match physical cores. Over-subscription causes CPU contention.',
 'Performance', 'Yarn', 'Yarn',
 '["CPU contention", "Unpredictable performance"]',
 '["Vcore over-subscription"]',
 '["Yarn"]',
 'When yarn.nodemanager.resource.cpu-vcores exceeds physical cores, containers compete for CPU causing context switch overhead.',
 'LOW', 'WARNING',
 '["Set yarn.nodemanager.resource.cpu-vcores = physical_cores - 2 (reserve for OS/DN/NM)", "For hyperthreaded systems, use physical cores not logical", "Enable CGroups for strict CPU isolation"]',
 '{"type": "always"}'),

('YARN-NM-MEMORY', 'YARN NodeManager memory allocation',
 'NodeManager allocatable memory should not exceed 80% of physical RAM to leave room for OS, DataNode, and other services.',
 'Performance', 'Yarn', 'Yarn',
 '["OOM kills", "System instability"]',
 '["Over-allocated NodeManager memory"]',
 '["Yarn", "Servers"]',
 'Over-allocating NM memory causes swapping and can trigger OOM killer on critical processes.',
 'HIGH', 'CRITICAL',
 '["Set yarn.nodemanager.resource.memory-mb = total_RAM_MB * 0.8", "Reserve at least 4GB for DataNode, 2GB for NodeManager, 2GB for OS", "For HBase colocated nodes, reserve additional memory for RegionServer", "Monitor actual memory usage vs allocation"]',
 '{"type": "always"}'),

('YARN-LOG-AGGREGATION', 'YARN log aggregation',
 'Log aggregation consolidates container logs to HDFS for post-mortem debugging. Critical for production clusters.',
 'Architecture', 'Yarn', 'Yarn',
 '["Loss of debugging capability"]',
 '["Log aggregation disabled"]',
 '["Yarn"]',
 'Without log aggregation, container logs are lost when NodeManager local storage is cleaned up, making debugging impossible.',
 'LOW', 'WARNING',
 '["Set yarn.log-aggregation-enable=true", "Set yarn.nodemanager.remote-app-log-dir=/app-logs", "Set yarn.nodemanager.log-aggregation.roll-monitoring-interval-seconds=3600", "Configure log retention: yarn.log-aggregation.retain-seconds=604800 (7 days)"]',
 '{"type": "metadata_check", "path": "yarn.log_aggregation.enabled", "operator": "equals", "expected": true}'),

('YARN-PREEMPTION', 'YARN preemption',
 'Preemption allows high-priority applications to reclaim resources from lower-priority ones. Essential for SLA enforcement.',
 'Performance', 'Yarn', 'Yarn',
 '["SLA breach", "Priority inversion"]',
 '["Preemption disabled"]',
 '["Yarn"]',
 'Without preemption, a low-priority batch job can block high-priority interactive queries indefinitely.',
 'MEDIUM', 'WARNING',
 '["Set yarn.resourcemanager.scheduler.monitor.enable=true", "Configure ProportionalCapacityPreemptionPolicy", "Set yarn.resourcemanager.monitor.capacity.preemption.total_preemption_per_round=0.1", "Test preemption behavior before enabling in production"]',
 '{"type": "metadata_check", "path": "yarn.preemption.enabled", "operator": "equals", "expected": true}'),

('YARN-LOCAL-DIRS', 'YARN NodeManager local directories',
 'Multiple local directories on separate disks provide parallelism for shuffle and reduce I/O bottlenecks.',
 'Performance', 'Yarn', 'Yarn',
 '["Shuffle bottleneck", "I/O contention"]',
 '["Single local directory"]',
 '["Yarn"]',
 'A single local directory creates an I/O hotspot during MapReduce shuffle, significantly slowing jobs.',
 'LOW', 'INFO',
 '["Configure yarn.nodemanager.local-dirs with one directory per physical disk", "Example: /data1/yarn/local,/data2/yarn/local,/data3/yarn/local", "Also configure yarn.nodemanager.log-dirs similarly", "Ensure all directories have sufficient space"]',
 '{"type": "always"}'),

('YARN-LINUX-CE', 'YARN Linux container executor',
 'Production clusters should use LinuxContainerExecutor instead of DefaultContainerExecutor for security and resource isolation.',
 'Security', 'Authorization', 'Yarn',
 '["Security bypass", "Resource isolation failure"]',
 '["Default container executor has no isolation"]',
 '["Yarn", "Servers"]',
 'DefaultContainerExecutor runs all containers as the NM user with no isolation. Any container can access other containers data.',
 'MEDIUM', 'WARNING',
 '["Set yarn.nodemanager.container-executor.class=LinuxContainerExecutor", "Configure container-executor.cfg with proper permissions", "Enable CGroups for CPU isolation", "Test thoroughly before enabling in production"]',
 '{"type": "metadata_check", "path": "yarn.cgroups_enabled", "operator": "equals", "expected": true}'),

-- ============================================================
-- IMPALA > BEST PRACTICES
-- ============================================================

('IMPALA-ADMISSION', 'Impala admission control',
 'Admission control prevents memory overcommit by queueing queries when resources are insufficient.',
 'Performance', 'Impala', 'Impala',
 '["Query failures from OOM", "Impala daemon crashes"]',
 '["No admission control — all queries execute immediately"]',
 '["Impala"]',
 'Without admission control, concurrent queries can exceed available memory, causing daemon crashes.',
 'HIGH', 'CRITICAL',
 '["Enable admission control in Impala configuration", "Configure memory limits per pool: request_pool_max_mem_limit", "Set queue timeout: request_pool_queue_timeout_ms=60000", "Create separate pools for interactive vs batch workloads"]',
 '{"type": "metadata_check", "path": "impala.admission_control.enabled", "operator": "equals", "expected": true}'),

('IMPALA-MEM-LIMIT', 'Impala daemon memory limit',
 'Each impalad should have a memory limit configured to prevent it from consuming all system memory.',
 'Performance', 'Impala', 'Impala',
 '["Daemon crash from OOM", "System instability"]',
 '["No memory limit configured"]',
 '["Impala", "Servers"]',
 'Without mem_limit, Impala uses all available memory, potentially starving other services.',
 'HIGH', 'CRITICAL',
 '["Set --mem_limit flag to 80% of available RAM on dedicated Impala nodes", "On shared nodes, allocate proportionally (e.g., 60%)", "Set per-query default: SET MEM_LIMIT=8g", "Monitor memory usage via Impala web UI (port 25000)"]',
 '{"type": "always"}'),

('IMPALA-SHORT-CIRCUIT', 'Impala short-circuit reads',
 'Short-circuit reads are mandatory for good Impala performance. Impala reads large amounts of data locally.',
 'Performance', 'Impala', 'HDFS',
 '["Severe read performance degradation"]',
 '["Short-circuit reads not enabled"]',
 '["Impala", "HDFS"]',
 'Without short-circuit reads, every Impala scan goes through DataNode RPC, adding massive overhead to query execution.',
 'HIGH', 'CRITICAL',
 '["Set dfs.client.read.shortcircuit=true in hdfs-site.xml", "Set dfs.domain.socket.path appropriately", "Ensure DataNodes and Impala daemons can access the domain socket", "This is a hard requirement for Impala — non-negotiable"]',
 '{"type": "metadata_check", "path": "hdfs.short_circuit_reads", "operator": "equals", "expected": true}'),

('IMPALA-SPILL', 'Impala scratch directories for spill',
 'Impala spills to disk when query memory exceeds limits. Multiple scratch directories on different disks prevent I/O bottleneck.',
 'Performance', 'Impala', 'Impala',
 '["Query slowdown during spill"]',
 '["Single or missing scratch directory"]',
 '["Impala"]',
 'A single scratch directory creates I/O contention during large sorts/joins that exceed memory.',
 'LOW', 'WARNING',
 '["Configure --scratch_dirs with one directory per physical disk", "Example: --scratch_dirs=/data1/impala/scratch,/data2/impala/scratch", "Ensure scratch directories have sufficient free space", "Monitor spill rates — frequent spilling indicates need for more memory"]',
 '{"type": "always"}'),

('IMPALA-STATS', 'Impala table/column statistics',
 'Impala optimizer relies on statistics for query planning. Missing stats lead to suboptimal query plans.',
 'Performance', 'Impala', 'Impala',
 '["Suboptimal query plans", "Poor join ordering"]',
 '["Missing or outdated statistics"]',
 '["Impala"]',
 'Without stats, Impala cannot estimate cardinality accurately, leading to wrong join strategies and excessive data shuffling.',
 'MEDIUM', 'WARNING',
 '["Run COMPUTE STATS on all frequently queried tables", "Schedule periodic COMPUTE INCREMENTAL STATS for partitioned tables", "Run COMPUTE STATS after major data loads", "Monitor query profiles for stats warnings"]',
 '{"type": "always"}'),

('IMPALA-PARQUET', 'Impala file format optimization',
 'Impala works best with Parquet format. Using text or other row-oriented formats severely degrades performance.',
 'Performance', 'Impala', 'Impala',
 '["Query performance degradation"]',
 '["Non-optimal file format"]',
 '["Impala"]',
 'Parquet provides columnar storage, predicate pushdown, and efficient compression — 10-100x faster than text for analytical queries.',
 'LOW', 'INFO',
 '["Convert tables to Parquet: CREATE TABLE new_table STORED AS PARQUET AS SELECT * FROM old_table", "Set default format: SET DEFAULT_FILE_FORMAT=parquet", "Use Snappy compression (default) for best speed/compression balance", "Partition large tables by date or category for scan efficiency"]',
 '{"type": "always"}'),

('IMPALA-CATALOG-MEM', 'Impala Catalog Server memory',
 'Catalog Server needs sufficient memory to cache metadata for all tables. Large clusters need 8-16GB.',
 'Performance', 'Impala', 'Impala',
 '["Metadata reload delays", "Query planning slow"]',
 '["Insufficient Catalog Server memory"]',
 '["Impala"]',
 'Catalog Server OOM causes metadata cache eviction, leading to slow query planning as metadata is reloaded.',
 'MEDIUM', 'WARNING',
 '["Set Catalog Server heap to 4-16GB depending on number of tables/partitions", "Monitor heap usage via Catalog web UI (port 25020)", "Consider increasing if catalog has >10000 tables or >100000 partitions"]',
 '{"type": "always"}'),

('IMPALA-STATESTORE', 'Impala StateStore health',
 'StateStore monitors all Impala daemons. If it fails, daemons cannot detect failures or receive metadata updates.',
 'Architecture', 'High Availability', 'Impala',
 '["Failure detection disabled", "Stale metadata"]',
 '["Single point of failure"]',
 '["Impala"]',
 'StateStore failure does not immediately kill queries but prevents new daemon registration and metadata propagation.',
 'MEDIUM', 'WARNING',
 '["Monitor StateStore health via web UI (port 25010)", "Set --statestore_subscriber_timeout_seconds appropriately (default 30s)", "Ensure StateStore is on a dedicated or lightly loaded host", "Monitor subscriber heartbeat latency"]',
 '{"type": "metadata_check", "path": "impala_metrics.service_info.has_statestore", "operator": "equals", "expected": true}'),

-- ============================================================
-- KUDU > BEST PRACTICES
-- ============================================================

('KUDU-NTP', 'Kudu time synchronization (strict)',
 'Kudu has a strict NTP requirement. Clock skew causes tablet leader election failures and write errors.',
 'Architecture', 'Kudu', 'Kudu',
 '["Write failures", "Leader election failures"]',
 '["Clock skew between nodes"]',
 '["Kudu"]',
 'Kudu uses hybrid logical clocks (HLC) that depend on NTP. Clock skew >500ms causes tablets to become unavailable.',
 'HIGH', 'CRITICAL',
 '["Install and configure NTP or chrony on ALL Kudu nodes", "Maximum allowed clock skew is 500ms (default)", "Monitor with: kudu cluster ksck", "Set --max_clock_sync_error_usec=10000000 only in development"]',
 '{"type": "metadata_check", "path": "system_info.ntp_status.source", "operator": "not_equals", "expected": "none"}'),

('KUDU-TSERVER-MEM', 'Kudu Tablet Server memory',
 'Tablet Server should have sufficient memory for block cache and maintenance operations.',
 'Performance', 'Kudu', 'Kudu',
 '["Performance degradation", "Compaction stalls"]',
 '["Insufficient Tablet Server memory"]',
 '["Kudu"]',
 'Low memory causes frequent cache evictions, slow scans, and compaction backlog.',
 'MEDIUM', 'WARNING',
 '["Set --memory_limit_hard_bytes to 80% of available RAM on dedicated nodes", "Set --block_cache_capacity_mb to 50% of memory limit", "Monitor memory usage via Kudu web UI (port 8050)", "Leave headroom for maintenance operations (compaction, flush)"]',
 '{"type": "always"}'),

('KUDU-REPLICATION', 'Kudu table replication factor',
 'Kudu tables should use replication factor 3 for production. Factor 1 means any tserver failure loses data.',
 'Architecture', 'Kudu', 'Kudu',
 '["Data loss", "Data unavailability"]',
 '["Insufficient replication"]',
 '["Kudu", "Data"]',
 'With replication factor 1, a single tserver disk failure permanently loses all data on that tablet.',
 'HIGH', 'CRITICAL',
 '["Create tables with replication factor 3: CREATE TABLE ... TBLPROPERTIES(kudu.num_replicas=3)", "Ensure at least 3 tservers for RF=3", "Use kudu table list to verify replication factors", "RF=1 is acceptable only for development/testing"]',
 '{"type": "always"}'),

('KUDU-TABLET-COUNT', 'Kudu tablets per Tablet Server',
 'Each Tablet Server should host fewer than 1000 tablets. Excessive tablets increase overhead and memory usage.',
 'Performance', 'Kudu', 'Kudu',
 '["Performance degradation", "Leader election storms"]',
 '["Too many tablets per server"]',
 '["Kudu"]',
 'Each tablet has fixed memory and thread overhead. Too many tablets exhaust resources and cause election storms.',
 'MEDIUM', 'WARNING',
 '["Aim for 20-40 tablets per table per tserver as a starting point", "Total should be <1000 tablets per tserver", "Use fewer partitions for small tables", "Monitor with: kudu tserver list"]',
 '{"type": "always"}'),

('KUDU-DEAD-TSERVER', 'Kudu dead Tablet Servers',
 'Dead Tablet Servers cause under-replicated tablets and potential data unavailability.',
 'Architecture', 'High Availability', 'Kudu',
 '["Data unavailability", "Under-replicated tablets"]',
 '["Tablet Server failure"]',
 '["Kudu"]',
 'Dead tservers cause tablets to lose one replica. If another tserver fails before re-replication, data may be lost.',
 'HIGH', 'CRITICAL',
 '["Check tserver process and logs", "Verify disk health on the host", "Run kudu cluster ksck to check cluster health", "Dead tservers trigger re-replication after raft_heartbeat_interval_ms timeout"]',
 '{"type": "threshold_check", "path": "kudu_metrics.kudu_master.num_tservers_dead", "threshold": 0, "direction": "above"}'),

('KUDU-MAINTENANCE', 'Kudu maintenance manager threads',
 'Maintenance manager threads handle compaction, flush, and delta apply. Default (1) is too few for most workloads.',
 'Performance', 'Kudu', 'Kudu',
 '["Compaction backlog", "Write stalls"]',
 '["Insufficient maintenance threads"]',
 '["Kudu"]',
 'With too few maintenance threads, compaction and flush operations fall behind, degrading read and write performance.',
 'LOW', 'WARNING',
 '["Set --maintenance_manager_num_threads=4 (or number of data disks, whichever is larger)", "Monitor compaction and flush queues via tserver metrics", "Increase for write-heavy workloads"]',
 '{"type": "always"}'),

('KUDU-WAL-DIR', 'Kudu WAL directory on dedicated disk',
 'Write-ahead log (WAL) should be on a dedicated, fast disk (SSD preferred) for optimal write performance.',
 'Performance', 'Kudu', 'Kudu',
 '["Write latency increase", "WAL sync bottleneck"]',
 '["WAL sharing disk with data or OS"]',
 '["Kudu"]',
 'WAL fsync latency directly impacts write latency. Sharing disk with data causes I/O contention.',
 'MEDIUM', 'WARNING',
 '["Set --fs_wal_dir to a dedicated SSD mount point", "Separate WAL disk from data disks (--fs_data_dirs)", "Monitor WAL sync latency via tserver metrics", "SSD for WAL gives the highest ROI for write performance"]',
 '{"type": "always"}'),

('KUDU-BLOCK-CACHE', 'Kudu block cache sizing',
 'Block cache should be sized at ~50% of memory limit for read-heavy workloads.',
 'Performance', 'Kudu', 'Kudu',
 '["Increased read latency"]',
 '["Suboptimal block cache size"]',
 '["Kudu"]',
 'Too small block cache causes excessive disk reads; too large starves maintenance operations.',
 'LOW', 'INFO',
 '["Set --block_cache_capacity_mb to ~50% of tserver memory limit", "For write-heavy workloads, reduce to 30-40%", "Monitor cache hit ratio via tserver metrics", "Aim for >90% cache hit rate for hot data"]',
 '{"type": "always"}');
