-- V5: Best-practice rules for Hive, ZooKeeper, Atlas, Ranger, NiFi, Kafka.

INSERT INTO recommendation_rules (code, title, description, category, subcategory, component, threat, vulnerability, asset, impact, default_likelihood, default_severity, recommendations_text, condition) VALUES

-- ============================================================
-- HIVE
-- ============================================================

('HIVE-ENGINE-TEZ', 'Hive execution engine should be Tez',
 'Tez provides significantly better performance than MapReduce for Hive queries through DAG execution, in-memory pipelining, and session reuse.',
 'Performance', 'Hive', 'Hive',
 '["Query performance degradation"]',
 '["Using legacy MapReduce execution engine"]',
 '["Hive"]',
 'MapReduce-based Hive is 5-10x slower than Tez for most query patterns due to disk I/O between stages.',
 'HIGH', 'CRITICAL',
 '["Set hive.execution.engine=tez in hive-site.xml", "Ensure Tez service is installed and configured", "Set tez.am.resource.memory.mb appropriately (1-4GB)", "Configure tez.runtime.io.sort.mb and tez.runtime.unordered.output.buffer.size-mb"]',
 '{"type": "metadata_check", "path": "hive_metrics.config.execution_engine", "operator": "equals", "expected": "tez"}'),

('HIVE-VECTORIZATION', 'Hive vectorized execution',
 'Vectorized query execution processes data in batches of 1024 rows instead of row-by-row, dramatically improving CPU utilization.',
 'Performance', 'Hive', 'Hive',
 '["Query performance degradation"]',
 '["Vectorized execution disabled"]',
 '["Hive"]',
 'Vectorization provides 2-10x speedup for scan-heavy queries on ORC/Parquet tables.',
 'MEDIUM', 'WARNING',
 '["Set hive.vectorized.execution.enabled=true", "Set hive.vectorized.execution.reduce.enabled=true", "Ensure tables use ORC or Parquet format for best vectorization support", "Test query performance before and after enabling"]',
 '{"type": "metadata_check", "path": "hive_metrics.config.vectorization_enabled", "operator": "equals", "expected": "true"}'),

('HIVE-CBO', 'Hive cost-based optimizer',
 'CBO uses table/column statistics to generate optimal query plans. Essential for complex queries with joins.',
 'Performance', 'Hive', 'Hive',
 '["Suboptimal query plans", "Slow joins"]',
 '["CBO disabled or missing statistics"]',
 '["Hive"]',
 'Without CBO, Hive uses rule-based optimization which cannot optimize join ordering or aggregation pushdown.',
 'MEDIUM', 'WARNING',
 '["Set hive.cbo.enable=true", "Set hive.compute.query.using.stats=true", "Run ANALYZE TABLE for all major tables", "Enable auto-gather: hive.stats.autogather=true"]',
 '{"type": "metadata_check", "path": "hive_metrics.config.cbo_enabled", "operator": "equals", "expected": "true"}'),

('HIVE-STATS-AUTOGATHER', 'Hive automatic statistics gathering',
 'Automatic stats gathering ensures optimizer statistics stay fresh after inserts and creates.',
 'Performance', 'Hive', 'Hive',
 '["Stale statistics", "Degraded query plans"]',
 '["Stats autogather disabled"]',
 '["Hive"]',
 'Without auto-gather, stats become stale after data loads, causing suboptimal join strategies.',
 'LOW', 'WARNING',
 '["Set hive.stats.autogather=true", "Run ANALYZE TABLE periodically for large tables with incremental loads", "Consider scheduling ANALYZE as part of ETL pipelines"]',
 '{"type": "metadata_check", "path": "hive_metrics.config.stats_autogather", "operator": "equals", "expected": "true"}'),

('HIVE-ORC-COMPRESSION', 'Hive ORC file compression',
 'ORC tables should use Snappy or Zlib compression to reduce storage and improve I/O performance.',
 'Performance', 'Hive', 'Hive',
 '["Storage waste", "Slower I/O"]',
 '["No compression configured"]',
 '["Hive", "HDFS"]',
 'Uncompressed ORC wastes 2-5x storage and reduces scan performance due to higher I/O volume.',
 'LOW', 'INFO',
 '["Set hive.exec.orc.default.compress=SNAPPY for best speed", "Use ZLIB for better compression ratio on cold data", "Set hive.exec.compress.output=true for intermediate data", "Verify with: DESCRIBE FORMATTED table_name"]',
 '{"type": "always"}'),

('HIVE-ACID', 'Hive ACID transactions',
 'ACID enables UPDATE, DELETE, MERGE, and transactional inserts in Hive. Required for data warehouse patterns.',
 'Performance', 'Hive', 'Hive',
 '["Data quality issues", "No update/delete capability"]',
 '["ACID not enabled"]',
 '["Hive"]',
 'Without ACID, data corrections require full partition rewrites, and concurrent writes can cause data corruption.',
 'LOW', 'INFO',
 '["Set hive.support.concurrency=true", "Set hive.enforce.bucketing=true", "Set hive.exec.dynamic.partition.mode=nonstrict", "Enable compaction: hive.compactor.initiator.on=true, hive.compactor.worker.threads=1"]',
 '{"type": "always"}'),

('HIVE-DYNAMIC-PARTITION', 'Hive dynamic partition mode',
 'Dynamic partition mode controls whether Hive allows fully dynamic partitioning in INSERT statements.',
 'Performance', 'Hive', 'Hive',
 '["ETL job failures", "Manual partition management overhead"]',
 '["Dynamic partition in strict mode"]',
 '["Hive"]',
 'Strict mode requires at least one static partition column, making automated ETL pipelines harder to build.',
 'LOW', 'INFO',
 '["Set hive.exec.dynamic.partition.mode=nonstrict for automated ETL", "Keep strict mode if partition explosion is a concern", "Set hive.exec.max.dynamic.partitions=1000 as a safety limit", "Set hive.exec.max.dynamic.partitions.pernode=100"]',
 '{"type": "always"}'),

('HIVE-MAPJOIN', 'Hive map-side join optimization',
 'Map-side joins avoid expensive shuffle operations by broadcasting small tables to all mappers.',
 'Performance', 'Hive', 'Hive',
 '["Slow join queries"]',
 '["Map join disabled or threshold too low"]',
 '["Hive"]',
 'Without map joins, even small dimension table lookups require a full shuffle sort-merge join.',
 'LOW', 'WARNING',
 '["Set hive.auto.convert.join=true", "Set hive.auto.convert.join.noconditionaltask.size=20971520 (20MB) or higher", "For Tez: set hive.auto.convert.join.noconditionaltask.size to 30-50% of Tez container size", "Ensure small dimension tables have ANALYZE TABLE statistics"]',
 '{"type": "metadata_check", "path": "hive_metrics.config.auto_convert_join", "operator": "equals", "expected": "true"}'),

('HIVE-HS2-HA', 'HiveServer2 high availability',
 'Multiple HiveServer2 instances should be deployed behind a load balancer or using ZooKeeper service discovery.',
 'Architecture', 'High Availability', 'Hive',
 '["Single point of failure", "Service interruption"]',
 '["Single HiveServer2 instance"]',
 '["Hive"]',
 'A single HS2 is a SPOF: its failure blocks all Hive queries and JDBC/ODBC connections.',
 'MEDIUM', 'WARNING',
 '["Deploy 2+ HiveServer2 instances", "Enable ZooKeeper service discovery: hive.server2.support.dynamic.service.discovery=true", "Configure hive.server2.zookeeper.namespace=hiveserver2", "Use a load balancer (HAProxy) for non-ZK clients"]',
 '{"type": "threshold_check", "path": "hive_metrics.service_info.hs2_count", "threshold": 1, "direction": "below", "absent_triggers": false}'),

-- ============================================================
-- ZOOKEEPER
-- ============================================================

('ZK-ODD-COUNT', 'ZooKeeper ensemble should have odd number of nodes',
 'ZooKeeper requires a majority (quorum) to operate. Odd numbers maximize fault tolerance per node.',
 'Architecture', 'ZooKeeper', 'ZooKeeper',
 '["Resource waste without fault tolerance gain"]',
 '["Even number of ZK nodes"]',
 '["ZooKeeper"]',
 'With 4 nodes, quorum is 3 — same as with 3 nodes. The 4th node adds cost without improving fault tolerance.',
 'LOW', 'WARNING',
 '["Use 3 nodes for small clusters (tolerates 1 failure)", "Use 5 nodes for large/critical clusters (tolerates 2 failures)", "Never use 1 node in production (no fault tolerance)", "7+ nodes is rarely justified — increases write latency"]',
 '{"type": "metadata_check", "path": "zookeeper_metrics.ensemble.is_odd_count", "operator": "equals", "expected": true}'),

('ZK-LEADER-ELECTED', 'ZooKeeper leader election',
 'The ensemble must have exactly one leader. Zero means election failure; more than one indicates split-brain.',
 'Architecture', 'ZooKeeper', 'ZooKeeper',
 '["Cluster-wide outage"]',
 '["Leader election failure"]',
 '["ZooKeeper", "HBase", "HDFS", "Kafka"]',
 'Without a leader, ZooKeeper cannot process writes. This blocks HBase, HDFS failover, and Kafka consumer group coordination.',
 'HIGH', 'CRITICAL',
 '["Check ZooKeeper logs for election errors", "Verify network connectivity between all ZK nodes", "Check for clock skew between ZK nodes", "Verify zoo.cfg is consistent across all nodes"]',
 '{"type": "metadata_check", "path": "zookeeper_metrics.ensemble.leaders", "operator": "equals", "expected": 1}'),

('ZK-OUTSTANDING-REQUESTS', 'ZooKeeper outstanding requests',
 'High outstanding request count indicates ZooKeeper is overloaded and cannot keep up with client requests.',
 'Performance', 'ZooKeeper', 'ZooKeeper',
 '["Increased latency", "Session timeouts"]',
 '["ZooKeeper overloaded"]',
 '["ZooKeeper", "HBase", "Kafka"]',
 'Outstanding requests cause increased latency for all ZK operations, potentially triggering HBase RegionServer and Kafka broker session timeouts.',
 'HIGH', 'WARNING',
 '["Investigate clients causing high request rates", "Increase ZK session timeout for affected services", "Consider dedicated ZK ensemble for different workloads", "Monitor with: echo mntr | nc localhost 2181"]',
 '{"type": "always"}'),

('ZK-DATADIR', 'ZooKeeper data directory on dedicated disk',
 'ZooKeeper transaction log should be on a dedicated disk to avoid I/O contention with OS and other services.',
 'Performance', 'ZooKeeper', 'ZooKeeper',
 '["Increased write latency", "Session timeouts"]',
 '["Shared disk for ZK transaction log"]',
 '["ZooKeeper"]',
 'ZK transaction log requires consistent low-latency writes. I/O contention causes write spikes that trigger session timeouts.',
 'MEDIUM', 'WARNING',
 '["Configure dataLogDir on a dedicated disk (preferably SSD)", "Separate dataDir and dataLogDir in zoo.cfg", "Ensure the disk has low latency (p99 < 10ms)", "Never share the ZK log disk with HDFS DataNode"]',
 '{"type": "always"}'),

('ZK-AUTOPURGE', 'ZooKeeper autopurge configuration',
 'ZooKeeper accumulates snapshots and transaction logs that must be periodically cleaned to avoid disk exhaustion.',
 'Architecture', 'ZooKeeper', 'ZooKeeper',
 '["Disk full", "ZooKeeper failure"]',
 '["No autopurge configured"]',
 '["ZooKeeper"]',
 'Without autopurge, ZK data directory grows indefinitely until disk is full, causing ZK and all dependent services to fail.',
 'MEDIUM', 'WARNING',
 '["Set autopurge.snapRetainCount=5 in zoo.cfg", "Set autopurge.purgeInterval=24 (hours)", "Verify with: ls -la /path/to/zk/data/version-2/"]',
 '{"type": "always"}'),

('ZK-FOUR-LETTER', 'ZooKeeper four-letter commands whitelisted',
 'Four-letter commands (mntr, stat, ruok) are essential for monitoring. They must be explicitly whitelisted since ZK 3.5.3.',
 'Architecture', 'ZooKeeper', 'ZooKeeper',
 '["Monitoring blind spot"]',
 '["Four-letter commands disabled by default"]',
 '["ZooKeeper"]',
 'Without mntr/stat, monitoring tools cannot collect ZK metrics, making performance issues invisible.',
 'LOW', 'INFO',
 '["Set 4lw.commands.whitelist=mntr,conf,ruok,stat,srvr,isro in zoo.cfg", "Or use the AdminServer REST API (port 8080) as an alternative", "Test with: echo mntr | nc localhost 2181"]',
 '{"type": "always"}'),

-- ============================================================
-- ATLAS
-- ============================================================

('ATLAS-ACTIVE', 'Atlas server active',
 'Atlas provides data governance, metadata management, and lineage tracking. It should be running and active.',
 'Architecture', 'Atlas', 'Atlas',
 '["No data governance", "No lineage tracking"]',
 '["Atlas server down or inactive"]',
 '["Atlas", "Data"]',
 'Without Atlas, there is no central metadata catalog or data lineage for compliance and impact analysis.',
 'MEDIUM', 'WARNING',
 '["Verify Atlas process is running", "Check Atlas logs for errors", "Verify Kafka (Atlas hook) and Solr/ES (index backend) are healthy", "Access Atlas UI at port 21000"]',
 '{"type": "metadata_check", "path": "atlas_metrics.service_info.is_active", "operator": "equals", "expected": true}'),

('ATLAS-HA', 'Atlas high availability',
 'Production Atlas should have multiple instances with active/passive failover for governance continuity.',
 'Architecture', 'High Availability', 'Atlas',
 '["Single point of failure for governance"]',
 '["Single Atlas instance"]',
 '["Atlas"]',
 'Atlas SPOF means metadata collection stops during outage. Hook events are queued in Kafka but lineage gaps may occur.',
 'LOW', 'WARNING',
 '["Deploy 2 Atlas instances in active/passive mode", "Configure atlas.server.ha.enabled=true", "Use ZooKeeper for leader election", "Ensure shared Solr/ES and Kafka backend"]',
 '{"type": "threshold_check", "path": "atlas_metrics.service_info.atlas_count", "threshold": 1, "direction": "below", "absent_triggers": false}'),

('ATLAS-SOLR-BACKEND', 'Atlas search index health',
 'Atlas depends on Solr or Elasticsearch for full-text search. Index health is critical for metadata discovery.',
 'Performance', 'Atlas', 'Atlas',
 '["Metadata search failures"]',
 '["Unhealthy search index"]',
 '["Atlas"]',
 'A degraded search index makes metadata discovery slow or impossible, defeating the purpose of a governance catalog.',
 'MEDIUM', 'WARNING',
 '["Monitor Solr/ES cluster health alongside Atlas", "Ensure Atlas Solr collections are replicated", "Schedule Solr optimize for large Atlas deployments", "Monitor Atlas entity count growth rate"]',
 '{"type": "always"}'),

-- ============================================================
-- RANGER
-- ============================================================

('RANGER-ACTIVE', 'Ranger Admin active',
 'Ranger provides centralized security policy management. It must be running for policy enforcement.',
 'Security', 'Authorization', 'Ranger',
 '["Security policy enforcement gap"]',
 '["Ranger Admin down"]',
 '["Ranger", "HDFS", "Hive", "HBase", "Kafka"]',
 'When Ranger Admin is down, plugins use cached policies. New policies cannot be created and audit is interrupted.',
 'HIGH', 'CRITICAL',
 '["Verify Ranger Admin process", "Check Ranger Admin logs", "Verify database connectivity (MySQL/PostgreSQL)", "Access Ranger UI at port 6080"]',
 '{"type": "metadata_check", "path": "ranger_metrics.service_info.is_active", "operator": "equals", "expected": true}'),

('RANGER-USERSYNC', 'Ranger UserSync running',
 'UserSync synchronizes users/groups from LDAP/AD into Ranger for policy assignment.',
 'Security', 'Authorization', 'Ranger',
 '["Stale user/group data", "New users cannot be granted access"]',
 '["UserSync not running"]',
 '["Ranger"]',
 'Without UserSync, new LDAP/AD users and group changes are not reflected in Ranger policies.',
 'MEDIUM', 'WARNING',
 '["Verify Ranger UserSync process is running", "Check UserSync logs for LDAP connection errors", "Verify LDAP/AD credentials in UserSync config", "Monitor sync interval and last sync time"]',
 '{"type": "threshold_check", "path": "ranger_metrics.service_info.usersync_count", "threshold": 0, "direction": "below", "absent_triggers": false}'),

('RANGER-AUDIT', 'Ranger audit logging',
 'Ranger audit logs all access decisions. Essential for compliance, forensics, and security monitoring.',
 'Security', 'Auditing', 'Ranger',
 '["No access audit trail", "Compliance violation"]',
 '["Audit logging disabled or misconfigured"]',
 '["Ranger", "Data"]',
 'Without audit logs, unauthorized access cannot be detected or investigated after the fact.',
 'HIGH', 'CRITICAL',
 '["Enable Ranger audit to Solr for searchable audit", "Enable Ranger audit to HDFS for long-term retention", "Set xasecure.audit.is.enabled=true in all Ranger plugins", "Monitor audit log volume and storage consumption"]',
 '{"type": "metadata_check", "path": "security.ranger.audit_enabled", "operator": "equals", "expected": true}'),

('RANGER-PLUGIN-SYNC', 'Ranger plugin policy sync',
 'All Ranger plugins should be syncing policies from Ranger Admin. Stale policies are a security risk.',
 'Security', 'Authorization', 'Ranger',
 '["Stale security policies", "Unauthorized access"]',
 '["Plugin sync failure"]',
 '["Ranger", "HDFS", "Hive", "HBase"]',
 'If plugins cannot sync, they use last-known policies. New deny rules wont take effect, potentially allowing unauthorized access.',
 'HIGH', 'WARNING',
 '["Check plugin logs for sync errors on each service host", "Verify Ranger Admin URL is reachable from all plugin hosts", "Check plugin cache directory for recent policy files", "Monitor policy version across all plugins"]',
 '{"type": "always"}'),

-- ============================================================
-- NIFI
-- ============================================================

('NIFI-CLUSTER', 'NiFi cluster mode',
 'Production NiFi should run in clustered mode for high availability and horizontal scaling.',
 'Architecture', 'High Availability', 'NiFi',
 '["Single point of failure", "Limited throughput"]',
 '["Standalone NiFi instance"]',
 '["NiFi"]',
 'Standalone NiFi is a SPOF. Cluster mode provides failover and distributes processing across nodes.',
 'MEDIUM', 'WARNING',
 '["Deploy NiFi in clustered mode with 3+ nodes", "Configure ZooKeeper for cluster coordination", "Set nifi.cluster.is.node=true", "Use a NiFi Registry for version-controlled flow management"]',
 '{"type": "metadata_check", "path": "nifi_metrics.service_info.is_clustered", "operator": "equals", "expected": true}'),

('NIFI-DISCONNECTED', 'NiFi disconnected nodes',
 'Disconnected NiFi nodes reduce cluster capacity and may cause data loss for site-to-site connections.',
 'Architecture', 'High Availability', 'NiFi',
 '["Reduced throughput", "Data routing failures"]',
 '["NiFi node disconnected from cluster"]',
 '["NiFi"]',
 'Disconnected nodes stop processing their share of data. If relationships are configured for failover, other nodes absorb the load.',
 'HIGH', 'CRITICAL',
 '["Check NiFi logs on disconnected nodes", "Verify ZooKeeper connectivity", "Check network connectivity between NiFi nodes", "Restart NiFi on affected nodes if needed"]',
 '{"type": "threshold_check", "path": "nifi_metrics.cluster.disconnected_nodes", "threshold": 0, "direction": "above"}'),

('NIFI-BACKPRESSURE', 'NiFi flowfile queue backpressure',
 'Queued flowfiles indicate processing bottlenecks. Excessive queuing can exhaust content repository storage.',
 'Performance', 'NiFi', 'NiFi',
 '["Data processing delays", "Content repository full"]',
 '["Processing bottleneck in flow"]',
 '["NiFi"]',
 'Large queues consume content repository space and increase processing latency. When content repo is full, NiFi stops accepting data.',
 'MEDIUM', 'WARNING',
 '["Identify bottleneck processors (check queue sizes in flow)", "Scale out: add NiFi nodes or increase processor concurrency", "Configure back-pressure thresholds on connections", "Monitor content repository usage: nifi_metrics.system_diagnostics"]',
 '{"type": "always"}'),

('NIFI-CONTENT-REPO', 'NiFi content repository storage',
 'Content repository stores flowfile data. Running out of space halts all data processing.',
 'Performance', 'NiFi', 'NiFi',
 '["Complete data processing halt"]',
 '["Content repository disk full"]',
 '["NiFi"]',
 'When content repository is full, NiFi cannot accept new data. All source processors stop and incoming connections back up.',
 'HIGH', 'CRITICAL',
 '["Use multiple content repository directories on different disks", "Set nifi.content.repository.directory.default and additional dirs", "Monitor free space and set alerts at 80% usage", "Configure content claim archiving: nifi.content.repository.archive.enabled=true"]',
 '{"type": "always"}'),

('NIFI-INVALID-PROCESSORS', 'NiFi invalid processors',
 'Invalid processors cannot execute. They indicate configuration errors that may break data flows.',
 'Architecture', 'NiFi', 'NiFi',
 '["Data flow broken", "Data loss"]',
 '["Processors with invalid configuration"]',
 '["NiFi"]',
 'Invalid processors silently fail to process data. Upstream queues fill up and downstream systems receive no data.',
 'MEDIUM', 'WARNING',
 '["Check each invalid processor configuration in NiFi UI", "Common causes: missing controller services, invalid file paths, expired credentials", "Validate flows before deployment using NiFi Registry", "Set up monitoring for processor state changes"]',
 '{"type": "threshold_check", "path": "nifi_metrics.flow_status.invalid_count", "threshold": 0, "direction": "above"}'),

('NIFI-PROVENANCE', 'NiFi provenance repository configuration',
 'Provenance records data lineage for each flowfile. Essential for debugging and compliance.',
 'Architecture', 'NiFi', 'NiFi',
 '["No data lineage audit trail"]',
 '["Provenance disabled or under-configured"]',
 '["NiFi"]',
 'Without provenance, you cannot trace where data came from, where it went, or why a transformation produced unexpected results.',
 'LOW', 'INFO',
 '["Enable provenance repository (default is enabled)", "Set retention: nifi.provenance.repository.max.storage.time=30 days", "Use Persistent provenance (not Volatile) for production", "Place provenance repository on fast storage (SSD)"]',
 '{"type": "always"}'),

-- ============================================================
-- KAFKA
-- ============================================================

('KAFKA-UNDER-REPLICATED', 'Kafka under-replicated partitions',
 'Under-replicated partitions have fewer in-sync replicas than configured. This risks data loss on broker failure.',
 'Architecture', 'High Availability', 'Kafka',
 '["Data loss risk", "Reduced fault tolerance"]',
 '["Broker failure", "Slow follower replicas"]',
 '["Kafka", "Data"]',
 'Under-replicated partitions are the #1 Kafka health indicator. Persistent under-replication indicates broker or disk issues.',
 'HIGH', 'CRITICAL',
 '["Check broker logs for replication errors", "Verify disk I/O on slow brokers", "Check network bandwidth between brokers", "Run kafka-topics.sh --describe to identify affected topics"]',
 '{"type": "always"}'),

('KAFKA-OFFLINE-PARTITIONS', 'Kafka offline partitions',
 'Offline partitions have no leader and cannot serve reads or writes. This is a production emergency.',
 'Architecture', 'High Availability', 'Kafka',
 '["Data unavailability", "Producer/consumer failures"]',
 '["All replicas for a partition are down"]',
 '["Kafka", "Data"]',
 'Offline partitions cause immediate producer errors and consumer lag. This blocks all services depending on those topics.',
 'HIGH', 'CRITICAL',
 '["Check all broker processes immediately", "Review broker logs for unclean shutdown or disk failures", "Run kafka-topics.sh --describe --unavailable-partitions", "Consider unclean.leader.election.enable=true only as last resort (data loss risk)"]',
 '{"type": "always"}'),

('KAFKA-REPLICATION', 'Kafka replication factor',
 'Production topics should have replication factor >= 3. Factor 1 means any broker failure loses data.',
 'Architecture', 'Kafka', 'Kafka',
 '["Data loss"]',
 '["Insufficient replication"]',
 '["Kafka", "Data"]',
 'With RF=1, a single broker disk failure permanently loses all data in its partitions.',
 'HIGH', 'CRITICAL',
 '["Create topics with --replication-factor 3", "Set default.replication.factor=3 in server.properties", "Use kafka-reassign-partitions.sh to increase RF for existing topics", "Ensure min.insync.replicas=2 with acks=all"]',
 '{"type": "always"}'),

('KAFKA-MIN-ISR', 'Kafka min.insync.replicas',
 'min.insync.replicas ensures a minimum number of replicas acknowledge writes with acks=all.',
 'Architecture', 'Kafka', 'Kafka',
 '["Silent data loss with acks=all"]',
 '["min.insync.replicas=1 (default)"]',
 '["Kafka", "Data"]',
 'With min.insync.replicas=1 and acks=all, a single replica acknowledgment suffices — no better than acks=1.',
 'HIGH', 'WARNING',
 '["Set min.insync.replicas=2 for RF=3 topics", "Set at broker level: min.insync.replicas=2 in server.properties", "Producers must use acks=all for this to be effective", "This ensures at least 2 replicas have the data before ack"]',
 '{"type": "always"}'),

('KAFKA-LOG-RETENTION', 'Kafka log retention configuration',
 'Log retention controls how long data is kept. Must be configured per use case to balance storage and data availability.',
 'Performance', 'Kafka', 'Kafka',
 '["Data loss from premature deletion", "Disk exhaustion from no retention"]',
 '["Default or misconfigured retention"]',
 '["Kafka"]',
 'Too short retention deletes data before consumers process it. Too long retention fills disks.',
 'MEDIUM', 'INFO',
 '["Set log.retention.hours=168 (7 days) as a reasonable default", "Use log.retention.bytes for size-based retention on constrained storage", "Configure per-topic retention for different SLAs", "Monitor disk usage on all broker log.dirs"]',
 '{"type": "always"}'),

('KAFKA-LOG-DIRS', 'Kafka multiple log directories',
 'Using multiple log directories on separate disks provides parallelism and fault tolerance.',
 'Performance', 'Kafka', 'Kafka',
 '["I/O bottleneck", "Single disk failure loses all data"]',
 '["Single log directory"]',
 '["Kafka"]',
 'A single log.dirs directory creates a SPOF and I/O bottleneck. Multiple disks improve throughput and resilience.',
 'MEDIUM', 'WARNING',
 '["Configure log.dirs with one directory per physical disk", "Example: log.dirs=/data1/kafka-logs,/data2/kafka-logs,/data3/kafka-logs", "Kafka 1.1+ supports JBOD: failed disk does not kill broker", "Monitor per-disk usage and I/O separately"]',
 '{"type": "always"}'),

('KAFKA-HEAP', 'Kafka broker heap sizing',
 'Kafka brokers typically need 4-8GB heap. More than 8GB rarely helps and increases GC pause risk.',
 'Performance', 'Kafka', 'Kafka',
 '["GC pauses causing request timeouts"]',
 '["Oversized or undersized broker heap"]',
 '["Kafka"]',
 'Kafka relies heavily on OS page cache, not JVM heap. Oversized heaps waste memory that would be better used for page cache.',
 'LOW', 'INFO',
 '["Set KAFKA_HEAP_OPTS=-Xmx6g -Xms6g (6GB is a good default)", "Use G1GC: -XX:+UseG1GC -XX:MaxGCPauseMillis=20", "Leave remaining RAM for OS page cache (critical for Kafka performance)", "Monitor GC pause times via JMX metrics"]',
 '{"type": "always"}'),

('KAFKA-NUM-PARTITIONS', 'Kafka partition count per topic',
 'Partition count determines parallelism and must balance throughput needs against overhead.',
 'Performance', 'Kafka', 'Kafka',
 '["Insufficient parallelism or excessive overhead"]',
 '["Suboptimal partition count"]',
 '["Kafka"]',
 'Too few partitions limit consumer parallelism. Too many increase ZK overhead, end-to-end latency, and rebalance time.',
 'LOW', 'INFO',
 '["Rule of thumb: partitions = max(throughput_target / throughput_per_partition, consumer_count)", "Start with 6-12 partitions per topic for most use cases", "Total partitions per broker should be <4000", "Increasing partitions is easy; decreasing requires topic recreation"]',
 '{"type": "always"}'),

('KAFKA-CONTROLLER', 'Kafka active controller',
 'The Kafka cluster must have exactly one active controller. Zero means cluster is headless.',
 'Architecture', 'High Availability', 'Kafka',
 '["No partition leadership changes", "No topic management"]',
 '["Controller election failure"]',
 '["Kafka"]',
 'Without a controller, no partition leader elections or reassignments can happen. New topic creation also fails.',
 'HIGH', 'CRITICAL',
 '["Check ZooKeeper health (Kafka controller relies on ZK)", "Verify all brokers can reach ZooKeeper", "Check broker logs for controller election errors", "Restart the broker that should be controller"]',
 '{"type": "always"}');
