-- V9: Advanced practices — governance, operational excellence, JVM tuning,
-- security deep, HA advanced, multi-tenancy, anti-patterns, infrastructure, ecosystem integrations.

INSERT INTO recommendation_rules (code, title, description, category, subcategory, component, threat, vulnerability, asset, impact, default_likelihood, default_severity, recommendations_text, condition) VALUES

-- ============================================================
-- GOVERNANCE & COMPLIANCE
-- ============================================================

('GOV-DATA-LIFECYCLE', 'Data lifecycle management policy',
 'A documented data lifecycle policy defines how data moves through hot/warm/cold tiers and when it is archived or deleted.',
 'Governance', 'Data Management', 'Platform',
 '["Uncontrolled storage growth", "Compliance violations"]',
 '["No lifecycle policy defined"]',
 '["HDFS", "Data"]',
 'Without lifecycle policies, data accumulates indefinitely, consuming expensive hot storage and violating retention requirements.',
 'HIGH', 'WARNING',
 '["Define lifecycle stages: hot (< 30 days), warm (30-180 days), cold (> 180 days), archive", "Implement automated tiering with HDFS storage policies or distcp to S3/ADLS", "Set retention periods per data classification", "Schedule automated purge jobs for expired data"]',
 '{"type": "always"}'),

('GOV-RETENTION-POLICY', 'Data retention policy enforcement',
 'Data retention policies must be enforced automatically to meet regulatory requirements.',
 'Governance', 'Compliance', 'Platform',
 '["Regulatory non-compliance", "Legal liability"]',
 '["No automated retention enforcement"]',
 '["Data"]',
 'Manual retention is error-prone. Regulatory fines for retaining data beyond mandated periods can be severe.',
 'HIGH', 'CRITICAL',
 '["Map data to regulatory frameworks (GDPR: personal data, SOX: financial, HIPAA: health)", "Implement automated deletion after retention period", "Maintain audit trail of all deletions", "Configure HDFS trash for safety (with shorter trash interval than retention)"]',
 '{"type": "always"}'),

('GOV-PII-CLASSIFICATION', 'PII and sensitive data classification',
 'All datasets containing personally identifiable information must be classified and tagged in the data catalog.',
 'Governance', 'Compliance', 'Atlas',
 '["Data breach liability", "Compliance violations"]',
 '["Unclassified PII data"]',
 '["Data", "Atlas"]',
 'Unclassified PII cannot be protected by Ranger policies or tracked for GDPR compliance.',
 'HIGH', 'CRITICAL',
 '["Use Atlas classifications for PII, PHI, PCI, CONFIDENTIAL", "Enable Atlas classification propagation for lineage-based tagging", "Run automated PII detection scans (regex for SSN, email, phone patterns)", "Map Ranger tag-based policies to Atlas classifications"]',
 '{"type": "always"}'),

('GOV-DATA-OWNER', 'Data ownership assignment',
 'Every dataset should have an identified owner responsible for quality, access, and lifecycle.',
 'Governance', 'Data Management', 'Atlas',
 '["No accountability for data quality"]',
 '["Orphaned datasets with no owner"]',
 '["Data"]',
 'Without owners, data quality degrades, access permissions stagnate, and nobody handles incidents.',
 'MEDIUM', 'WARNING',
 '["Assign ownership as Atlas business metadata on every table/database", "Include owner in table properties: TBLPROPERTIES(data_owner=team@company)", "Automate owner assignment in onboarding workflows", "Review and update ownership quarterly"]',
 '{"type": "always"}'),

('GOV-LINEAGE-COMPLETENESS', 'Data lineage coverage',
 'Atlas lineage should capture end-to-end data flow from ingestion to consumption.',
 'Governance', 'Data Management', 'Atlas',
 '["Incomplete impact analysis", "Cannot trace data origins"]',
 '["Lineage gaps between services"]',
 '["Atlas", "Data"]',
 'Without complete lineage, impact analysis for schema changes or data quality issues is impossible.',
 'MEDIUM', 'WARNING',
 '["Configure Atlas hooks for all data-producing services (Hive, Spark, Kafka, Sqoop, NiFi)", "Verify lineage chain in Atlas UI from source to consumption", "Monitor hook Kafka topic for dropped events", "Fill manual lineage gaps with Atlas REST API"]',
 '{"type": "always"}'),

('GOV-ORPHANED-DATA', 'Orphaned data detection',
 'Data in HDFS that is not referenced by any catalog entry or active pipeline represents waste and potential compliance risk.',
 'Governance', 'Data Management', 'HDFS',
 '["Storage waste", "Compliance risk from unmanaged data"]',
 '["No orphan detection process"]',
 '["HDFS", "Data"]',
 'Orphaned data grows silently and may contain sensitive information outside governance scope.',
 'MEDIUM', 'WARNING',
 '["Periodically scan HDFS paths against Hive Metastore and Atlas catalog", "Flag directories not referenced by any table, view, or lineage entity", "Implement quarantine process: move orphans to staging area before deletion", "Set up alerts for new unregistered HDFS paths"]',
 '{"type": "always"}'),

('GOV-SCHEMA-REGISTRY', 'Schema registry for streaming data',
 'A schema registry enforces schema compatibility for Kafka topics and prevents breaking changes.',
 'Governance', 'Data Management', 'Kafka',
 '["Data corruption from incompatible schemas"]',
 '["No schema enforcement on Kafka topics"]',
 '["Kafka", "Data"]',
 'Without schema registry, producers can send arbitrary formats causing consumer failures.',
 'MEDIUM', 'WARNING',
 '["Deploy Confluent Schema Registry or Hortonworks Schema Registry", "Register Avro/Protobuf schemas for all production topics", "Set compatibility mode: BACKWARD or FULL for evolution safety", "Integrate with Kafka producers via serializer configuration"]',
 '{"type": "always"}'),

('GOV-DATA-QUALITY', 'Data quality monitoring',
 'Automated data quality checks should validate completeness, accuracy, and freshness of critical datasets.',
 'Governance', 'Data Management', 'Platform',
 '["Incorrect analytics", "Bad business decisions"]',
 '["No data quality monitoring"]',
 '["Data"]',
 'Data quality issues propagate through pipelines silently until they affect reports or ML models.',
 'MEDIUM', 'WARNING',
 '["Implement data quality rules: null rate, uniqueness, referential integrity, freshness", "Use tools like Great Expectations, Deequ, or custom Spark checks", "Alert on quality metric threshold breaches", "Track data quality scores over time per dataset"]',
 '{"type": "always"}'),

('GOV-CATALOG-COVERAGE', 'Metadata catalog coverage',
 'All production tables and datasets should be cataloged with descriptions, owners, and classifications.',
 'Governance', 'Data Management', 'Atlas',
 '["Data discovery impossible"]',
 '["Undocumented datasets"]',
 '["Atlas", "Data"]',
 'Uncataloged data is undiscoverable, leading to duplication and wasted compute.',
 'LOW', 'WARNING',
 '["Track catalog coverage: % of tables with descriptions, owners, classifications", "Target >90% coverage for production databases", "Integrate catalog update into CI/CD pipelines", "Run periodic audits of uncataloged tables"]',
 '{"type": "always"}'),

('GOV-ERASURE-CAPABILITY', 'Right to erasure capability (GDPR)',
 'The platform must support deletion of all data related to a specific individual upon request.',
 'Governance', 'Compliance', 'Platform',
 '["GDPR violation", "Regulatory fines"]',
 '["Cannot identify and delete individual data"]',
 '["Data"]',
 'GDPR Article 17 requires deletion within 30 days. Without technical capability, this is impossible.',
 'HIGH', 'CRITICAL',
 '["Implement data subject identification across all stores (HDFS, HBase, Kafka)", "Build erasure pipeline: identify → verify → delete → audit trail", "Test erasure end-to-end including derived/downstream data", "Document erasure process for regulatory auditors"]',
 '{"type": "always"}'),

-- ============================================================
-- OPERATIONAL EXCELLENCE
-- ============================================================

('OPS-CHANGE-MGMT', 'Change management process',
 'All configuration and infrastructure changes should follow a documented change management process.',
 'Operations', 'Process', 'Platform',
 '["Unplanned outages from untested changes"]',
 '["Ad-hoc changes without review"]',
 '["Servers"]',
 'Uncontrolled changes are the leading cause of production incidents.',
 'HIGH', 'WARNING',
 '["Implement change approval workflow (JIRA, ServiceNow)", "Require peer review for all config changes", "Maintain change log with rollback instructions", "Schedule changes during maintenance windows"]',
 '{"type": "always"}'),

('OPS-RUNBOOK', 'Operational runbooks',
 'Runbooks document step-by-step procedures for common operational tasks and incident response.',
 'Operations', 'Process', 'Platform',
 '["Slow incident response", "Tribal knowledge dependency"]',
 '["No documented procedures"]',
 '["Servers"]',
 'Without runbooks, incident response depends on individual expertise, creating single points of knowledge failure.',
 'MEDIUM', 'WARNING',
 '["Create runbooks for: service restart, failover, data recovery, scaling, common errors", "Include diagnostic steps, commands, expected outputs", "Store in version control alongside infrastructure code", "Review and update runbooks after each incident"]',
 '{"type": "always"}'),

('OPS-INCIDENT-RESPONSE', 'Incident response plan',
 'A documented incident response plan ensures fast, coordinated handling of production issues.',
 'Operations', 'Process', 'Platform',
 '["Slow or chaotic incident handling"]',
 '["No incident response plan"]',
 '["Servers"]',
 'Without a plan, incidents escalate slowly, communication is inconsistent, and resolution is delayed.',
 'HIGH', 'CRITICAL',
 '["Define severity levels (P1-P4) with response time SLAs", "Establish on-call rotation and escalation paths", "Set up incident communication channels (Slack, PagerDuty, bridge call)", "Conduct post-incident reviews (blameless post-mortems)"]',
 '{"type": "always"}'),

('OPS-PATCH-MGMT', 'Security patch management',
 'Critical security patches should be tested and deployed within defined SLAs.',
 'Operations', 'Security', 'Platform',
 '["Exploitation of known vulnerabilities"]',
 '["Delayed or missing security patches"]',
 '["Servers"]',
 'Known CVEs are actively exploited. Delayed patching leaves the cluster vulnerable.',
 'HIGH', 'CRITICAL',
 '["Define patch SLAs: Critical=7 days, High=30 days, Medium=90 days", "Test patches in staging before production", "Track patch compliance across all nodes", "Subscribe to vendor security advisories"]',
 '{"type": "always"}'),

('OPS-HEALTH-CHECKS', 'Automated health checks',
 'Automated health checks should validate cluster state beyond basic service health.',
 'Operations', 'Monitoring', 'Platform',
 '["Silent degradation undetected"]',
 '["Only basic Ambari alerts"]',
 '["Servers"]',
 'Basic health checks miss data consistency, performance degradation, and capacity exhaustion.',
 'MEDIUM', 'WARNING',
 '["Implement HDFS fsck periodic checks (weekly)", "Validate HBase hbck status (weekly)", "Check Kafka consumer lag across all groups", "Validate end-to-end data pipeline freshness"]',
 '{"type": "always"}'),

('OPS-SLO-SLI', 'Service Level Objectives (SLO/SLI)',
 'Defined SLOs with measurable SLIs enable data-driven reliability decisions.',
 'Operations', 'Monitoring', 'Platform',
 '["No reliability targets", "Cannot measure service quality"]',
 '["No SLO/SLI defined"]',
 '["Servers"]',
 'Without SLOs, there is no objective measure of whether the platform meets user expectations.',
 'MEDIUM', 'WARNING',
 '["Define SLOs for: availability (99.9%), query latency (p99 < 5s), data freshness (< 1h)", "Implement SLI dashboards tracking actual vs target", "Set error budget policies: freeze changes when budget exhausted", "Review SLOs quarterly with stakeholders"]',
 '{"type": "always"}'),

('OPS-ALERT-FATIGUE', 'Alert fatigue prevention',
 'Too many noisy alerts cause operators to ignore critical ones. Each alert should be actionable.',
 'Operations', 'Monitoring', 'Platform',
 '["Critical alerts missed in noise"]',
 '["Too many non-actionable alerts"]',
 '["Servers"]',
 'Alert fatigue is the #1 cause of missed incidents. When everything is urgent, nothing is.',
 'MEDIUM', 'WARNING',
 '["Audit all alerts: delete non-actionable ones", "Ensure every alert has a runbook link", "Implement alert deduplication and grouping", "Track alert-to-incident ratio — target >50% signal rate"]',
 '{"type": "always"}'),

('OPS-POST-MORTEM', 'Post-incident reviews',
 'Blameless post-mortems after incidents prevent recurrence and build organizational learning.',
 'Operations', 'Process', 'Platform',
 '["Recurring incidents"]',
 '["No root cause analysis"]',
 '["Servers"]',
 'Without post-mortems, the same failures repeat. Root causes are never addressed.',
 'MEDIUM', 'WARNING',
 '["Conduct post-mortems for all P1/P2 incidents within 48 hours", "Document: timeline, root cause, contributing factors, action items", "Track action item completion", "Share learnings across the organization"]',
 '{"type": "always"}'),

-- ============================================================
-- JVM & I/O TUNING
-- ============================================================

('JVM-GC-SELECTION', 'JVM GC algorithm per service',
 'Each service should use the optimal GC algorithm for its heap size and latency requirements.',
 'Performance', 'JVM', 'Platform',
 '["GC pauses causing timeouts"]',
 '["Suboptimal GC algorithm"]',
 '["Servers"]',
 'Wrong GC algorithm causes long pauses (CMS with large heaps) or low throughput (G1 with small heaps).',
 'MEDIUM', 'WARNING',
 '["Heap <8GB: CMS or Parallel GC", "Heap 8-32GB: G1GC (-XX:+UseG1GC -XX:MaxGCPauseMillis=100)", "Heap >32GB: ZGC or Shenandoah (if JDK11+)", "Match GC to service SLA: low-latency (HBase RS) = G1/ZGC, throughput (MapReduce) = Parallel"]',
 '{"type": "always"}'),

('JVM-GC-LOGGING', 'GC logging enabled for all services',
 'GC logs are essential for diagnosing memory issues and tuning heap configuration.',
 'Performance', 'JVM', 'Platform',
 '["Cannot diagnose GC issues"]',
 '["GC logging disabled"]',
 '["Servers"]',
 'Without GC logs, you cannot determine if pauses are caused by GC, what type of collections occur, or when heap is exhausted.',
 'LOW', 'WARNING',
 '["Enable for all Java services: -Xloggc:/var/log/service/gc.log -XX:+PrintGCDetails -XX:+PrintGCDateStamps", "JDK9+: -Xlog:gc*:file=/var/log/service/gc.log:time,uptime,level,tags", "Configure log rotation: -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=5 -XX:GCLogFileSize=20M", "Review GC logs periodically for long pauses"]',
 '{"type": "always"}'),

('JVM-FLAGS-OPT', 'Recommended JVM flags',
 'Standard JVM optimization flags should be applied to all Hadoop services.',
 'Performance', 'JVM', 'Platform',
 '["Suboptimal JVM performance"]',
 '["Default JVM flags"]',
 '["Servers"]',
 'Missing standard flags leave performance on the table.',
 'LOW', 'INFO',
 '["Always: -XX:+UseCompressedOops (for heaps <32GB), -XX:+AlwaysPreTouch", "G1GC: -XX:+ParallelRefProcEnabled -XX:G1HeapRegionSize=16m", "Memory: -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=512m", "Strings: -XX:+UseStringDeduplication (G1GC only, saves 5-10% heap)"]',
 '{"type": "always"}'),

('IO-READAHEAD', 'Disk read-ahead optimization',
 'Read-ahead buffer size affects sequential read performance. Default 128KB is too low for Hadoop.',
 'Performance', 'Disk', 'OS',
 '["Reduced sequential read throughput"]',
 '["Default read-ahead too small"]',
 '["HDFS", "Servers"]',
 'Hadoop reads large blocks sequentially. Larger read-ahead allows the kernel to prefetch data efficiently.',
 'LOW', 'INFO',
 '["Set read-ahead to 4096 sectors (2MB): blockdev --setra 4096 /dev/sdX", "Apply to all data disks", "Persist in udev rules or rc.local", "Verify: blockdev --getra /dev/sdX"]',
 '{"type": "always"}'),

('IO-SCHEDULER-OPT', 'I/O scheduler per disk type',
 'Different disk types require different I/O schedulers for optimal performance.',
 'Performance', 'Disk', 'OS',
 '["Suboptimal disk performance"]',
 '["Default I/O scheduler not optimal"]',
 '["Servers"]',
 'CFQ (default) is not optimal for SSDs. Deadline/noop/none reduce latency for SSDs.',
 'LOW', 'INFO',
 '["SSD: use noop or none (echo noop > /sys/block/sdX/queue/scheduler)", "HDD: use deadline for low-latency or cfq for fairness", "NVMe: kernel default (none/mq-deadline) is typically optimal", "Persist via udev rules"]',
 '{"type": "always"}'),

('COMPRESS-CODEC', 'Compression codec selection per use case',
 'Different workloads benefit from different compression codecs. One size does not fit all.',
 'Performance', 'Data Management', 'Platform',
 '["Suboptimal compression/decompression tradeoff"]',
 '["Single codec for all data"]',
 '["HDFS", "Data"]',
 'Using Gzip everywhere wastes CPU; using Snappy on cold data wastes storage.',
 'LOW', 'INFO',
 '["Hot/real-time data: Snappy or LZ4 (fast compress/decompress, moderate ratio)", "Warm analytical data: ZSTD (good balance of speed and ratio)", "Cold/archive data: Gzip or ZSTD level 19 (best ratio, slower)", "Intermediate shuffle data: LZ4 (fastest)"]',
 '{"type": "always"}'),

-- ============================================================
-- SECURITY DEEP
-- ============================================================

('SEC-NET-SEGMENTATION', 'Network segmentation',
 'Cluster nodes should be in a separate network segment from user workstations and internet-facing services.',
 'Security', 'Network', 'Network',
 '["Lateral movement from compromised workstation"]',
 '["Flat network topology"]',
 '["Servers", "Data"]',
 'On a flat network, a compromised user machine has direct access to DataNode and RegionServer ports.',
 'HIGH', 'CRITICAL',
 '["Place cluster nodes in dedicated VLANs", "Implement firewall rules between cluster and corporate network", "Expose only gateway services (Knox, HS2, Impala) to user networks", "Use jump hosts for admin access to cluster nodes"]',
 '{"type": "always"}'),

('SEC-KEY-ROTATION', 'Encryption key rotation',
 'Encryption keys should be rotated on a defined schedule to limit exposure window if compromised.',
 'Security', 'Data Protection', 'Ranger',
 '["Extended exposure from compromised keys"]',
 '["No key rotation schedule"]',
 '["Data"]',
 'Long-lived keys increase the window of vulnerability. If a key is compromised, all data encrypted with it is at risk.',
 'MEDIUM', 'WARNING',
 '["Rotate HDFS encryption zone keys annually via Ranger KMS", "Rotate Kerberos service keytabs annually", "Rotate SSL certificates before expiry (90 days for public CA)", "Maintain key versioning for graceful rollover"]',
 '{"type": "always"}'),

('SEC-AUDIT-INTEGRITY', 'Audit log integrity',
 'Audit logs must be tamper-proof to be valid for compliance and forensics.',
 'Security', 'Auditing', 'Ranger',
 '["Tampered audit logs", "Compliance invalidity"]',
 '["Audit logs stored in mutable location"]',
 '["Data"]',
 'If an attacker can modify audit logs, their unauthorized access is invisible to investigators.',
 'MEDIUM', 'CRITICAL',
 '["Ship Ranger audit logs to immutable storage (WORM, HDFS append-only)", "Forward to SIEM system in real-time (Splunk, ELK)", "Enable audit log checksums", "Restrict write access to audit log directories"]',
 '{"type": "always"}'),

('SEC-LEAST-PRIVILEGE', 'Principle of least privilege',
 'Every service account and user should have only the minimum permissions required for their function.',
 'Security', 'Authorization', 'Ranger',
 '["Excessive access", "Lateral movement"]',
 '["Overly permissive policies"]',
 '["Data"]',
 'Over-privileged accounts amplify the impact of any credential compromise.',
 'HIGH', 'WARNING',
 '["Audit Ranger policies for wildcard (*) permissions — replace with specific access", "Review user-to-role mappings quarterly", "Remove access for deactivated users within 24 hours", "Implement just-in-time access for admin operations"]',
 '{"type": "always"}'),

('SEC-SERVICE-ACCOUNTS', 'Service account management',
 'Service accounts should be inventoried, documented, and have their credentials rotated.',
 'Security', 'Access', 'Platform',
 '["Credential compromise"]',
 '["Undocumented service accounts"]',
 '["Servers"]',
 'Unknown service accounts cannot be monitored or secured. They often have excessive privileges.',
 'MEDIUM', 'WARNING',
 '["Inventory all service accounts with their purpose and owner", "Ensure each service uses a dedicated account (not shared)", "Rotate credentials on a defined schedule", "Monitor service account activity for anomalies"]',
 '{"type": "always"}'),

('SEC-CVE-SCANNING', 'Vulnerability scanning',
 'Regular CVE scanning identifies known vulnerabilities in installed software and libraries.',
 'Security', 'Patching', 'Platform',
 '["Exploitation of known CVEs"]',
 '["No vulnerability scanning"]',
 '["Servers"]',
 'Unscanned systems may have critical vulnerabilities with public exploits available.',
 'HIGH', 'CRITICAL',
 '["Integrate vulnerability scanner (Nessus, Qualys, Trivy) into CI/CD", "Scan all nodes monthly at minimum", "Track CVE remediation SLA compliance", "Subscribe to Apache security mailing lists for all installed projects"]',
 '{"type": "always"}'),

('SEC-SIEM-INTEGRATION', 'SIEM integration',
 'Security events should be forwarded to a SIEM for correlation, alerting, and forensic analysis.',
 'Security', 'Auditing', 'Platform',
 '["Cannot detect multi-stage attacks"]',
 '["Security events siloed in individual logs"]',
 '["Servers", "Data"]',
 'Without SIEM correlation, attacks spanning multiple services go undetected.',
 'MEDIUM', 'WARNING',
 '["Forward Ranger audit, OS auth logs, and firewall logs to SIEM", "Create correlation rules for: privilege escalation, unusual data access, brute force", "Set up real-time alerts for critical security events", "Retain security logs per compliance requirements"]',
 '{"type": "always"}'),

-- ============================================================
-- HA ADVANCED
-- ============================================================

('HA-FAILOVER-TESTING', 'Periodic failover testing',
 'Automatic failover should be tested regularly to ensure it works when needed.',
 'Architecture', 'High Availability', 'Platform',
 '["Failover fails when needed"]',
 '["Failover never tested"]',
 '["HDFS", "Yarn", "HBase"]',
 'Untested failover is theoretical failover. Configuration drift can break it silently.',
 'HIGH', 'CRITICAL',
 '["Test HDFS NameNode failover quarterly", "Test YARN ResourceManager failover quarterly", "Test HBase Master failover quarterly", "Document failover time and validate against RTO SLA"]',
 '{"type": "always"}'),

('HA-SPLIT-BRAIN', 'Split-brain prevention (fencing)',
 'Fencing mechanisms must be configured to prevent split-brain scenarios during failover.',
 'Architecture', 'High Availability', 'Platform',
 '["Data corruption from dual-master writes"]',
 '["No fencing configured"]',
 '["HDFS", "HBase"]',
 'Split-brain causes two masters to accept writes simultaneously, leading to data corruption.',
 'HIGH', 'CRITICAL',
 '["Configure STONITH fencing for HDFS HA: dfs.ha.fencing.methods=sshfence,shell", "Verify fencing works: simulate failover and verify old master is stopped", "For HBase: ensure ZooKeeper quorum properly detects master failure", "Monitor fencing log for failures"]',
 '{"type": "always"}'),

('HA-GRACEFUL-SHUTDOWN', 'Graceful shutdown configuration',
 'Services should have appropriate shutdown timeouts to drain in-flight operations.',
 'Architecture', 'High Availability', 'Platform',
 '["Data loss from hard kills"]',
 '["No graceful shutdown configured"]',
 '["Servers"]',
 'Hard kills during shutdown can lose in-flight writes and corrupt state.',
 'LOW', 'WARNING',
 '["Configure YARN decommission timeout: yarn.resourcemanager.nodemanager-graceful-decommission-timeout-secs", "Configure HBase graceful stop: hbase.regionserver.shutdown.wait.time", "Ensure systemd service files have TimeoutStopSec matching shutdown timeout", "Test graceful shutdown with in-flight operations"]',
 '{"type": "always"}'),

-- ============================================================
-- MULTI-TENANCY
-- ============================================================

('MT-YARN-HARD-LIMITS', 'YARN queue hard resource limits',
 'YARN queue maximum capacity should enforce hard limits to prevent one tenant from consuming all resources.',
 'Performance', 'Multi-tenancy', 'Yarn',
 '["Resource starvation for other tenants"]',
 '["Only soft limits configured"]',
 '["Yarn"]',
 'Without hard limits, a single tenant burst can consume the entire cluster.',
 'MEDIUM', 'WARNING',
 '["Set maximum-capacity per queue (not just capacity)", "Example: queue A capacity=40, maximum-capacity=60", "Enable preemption to reclaim resources from overusing queues", "Monitor per-queue utilization vs limits"]',
 '{"type": "always"}'),

('MT-HDFS-QUOTAS-TENANT', 'Per-tenant HDFS quotas',
 'Each tenant should have storage and namespace quotas to prevent resource abuse.',
 'Performance', 'Multi-tenancy', 'HDFS',
 '["HDFS filled by one tenant"]',
 '["No per-tenant quotas"]',
 '["HDFS"]',
 'A runaway ETL job from one tenant can fill the entire cluster, affecting all tenants.',
 'MEDIUM', 'WARNING',
 '["Set space quotas per tenant directory: hdfs dfsadmin -setSpaceQuota", "Set namespace quotas to prevent small file abuse", "Monitor quota usage and alert at 80%", "Include quota allocation in tenant onboarding process"]',
 '{"type": "always"}'),

('MT-RANGER-ISOLATION', 'Cross-tenant data isolation',
 'Ranger policies must prevent tenants from accessing each other data.',
 'Security', 'Multi-tenancy', 'Ranger',
 '["Cross-tenant data access"]',
 '["Shared Ranger policies"]',
 '["Data"]',
 'Without isolation, one compromised tenant account can access all data on the cluster.',
 'HIGH', 'CRITICAL',
 '["Implement deny-by-default Ranger policies per tenant", "Use row-level filtering for shared tables", "Audit cross-tenant access attempts regularly", "Test isolation: verify tenant A cannot access tenant B directories"]',
 '{"type": "always"}'),

('MT-RESOURCE-ACCOUNTING', 'Resource consumption tracking per tenant',
 'Resource usage (compute, storage, I/O) should be tracked per tenant for chargeback.',
 'Operations', 'Multi-tenancy', 'Platform',
 '["No usage accountability"]',
 '["Cannot attribute resource costs"]',
 '["Yarn", "HDFS"]',
 'Without tracking, heavy users subsidized by light users, creating resentment and waste.',
 'LOW', 'WARNING',
 '["Use YARN queue metrics for compute attribution", "Use HDFS quota reports for storage attribution", "Export usage data to billing/chargeback system", "Publish monthly usage reports per tenant"]',
 '{"type": "always"}'),

-- ============================================================
-- ANTI-PATTERNS & EDGE CASES
-- ============================================================

('AP-SMALL-FILES-DETECT', 'Small files detection',
 'Small files (much smaller than HDFS block size) waste NameNode memory and degrade performance.',
 'Performance', 'HDFS', 'HDFS',
 '["NameNode memory exhaustion", "Slow MapReduce/Spark jobs"]',
 '["Many small files from ingestion pipelines"]',
 '["HDFS"]',
 'Each file/block uses ~150 bytes of NameNode memory. 100M small files = 15GB of NameNode heap wasted.',
 'HIGH', 'WARNING',
 '["Monitor average block size: should be >64MB for healthy clusters", "Consolidate small files using: HAR (Hadoop Archive), CombineFileInputFormat, compaction", "Fix at source: configure Flume/NiFi to write larger files", "Set Hive to merge small files: hive.merge.mapfiles=true, hive.merge.smallfiles.avgsize=128000000"]',
 '{"type": "always"}'),

('AP-HBASE-HOTSPOT', 'HBase row key hotspotting',
 'Sequential or monotonically increasing row keys cause all writes to land on a single RegionServer.',
 'Performance', 'HBase', 'HBase',
 '["Single RegionServer overloaded", "Write throughput limited to one server"]',
 '["Sequential row keys (timestamp, auto-increment)"]',
 '["HBase"]',
 'Hotspotting reduces write throughput to 1/N of the cluster capacity (N = number of RegionServers).',
 'HIGH', 'CRITICAL',
 '["Salt row keys: prefix with hash(key) mod N", "Reverse timestamps: Long.MAX_VALUE - timestamp", "Use random UUIDs for write-heavy tables", "Pre-split tables with expected key distribution"]',
 '{"type": "always"}'),

('AP-KAFKA-LAG-SLA', 'Kafka consumer lag SLA',
 'Consumer lag should be monitored against defined SLAs to ensure timely processing.',
 'Performance', 'Kafka', 'Kafka',
 '["Stale data in downstream systems"]',
 '["Consumer lag growing without alerts"]',
 '["Kafka"]',
 'Growing consumer lag means downstream systems serve stale data, affecting decisions.',
 'HIGH', 'WARNING',
 '["Define lag SLA per consumer group (e.g., <1000 messages or <5 minutes)", "Monitor with: kafka-consumer-groups.sh --describe --group name", "Alert when lag exceeds SLA threshold", "Root cause analysis: slow consumer, rebalancing, or partition skew"]',
 '{"type": "always"}'),

('AP-SPARK-SKEW', 'Spark data skew detection',
 'Data skew causes some tasks to process orders of magnitude more data than others.',
 'Performance', 'Spark', 'Spark',
 '["Job bottlenecked by slowest task"]',
 '["Skewed join or group-by keys"]',
 '["Spark"]',
 'A single skewed partition can take 100x longer than others, negating parallelism.',
 'MEDIUM', 'WARNING',
 '["Enable AQE skew join handling: spark.sql.adaptive.skewJoin.enabled=true", "Monitor task duration variance in Spark UI stages", "Salt skewed keys: add random prefix, aggregate twice", "Use broadcast join for small dimension tables"]',
 '{"type": "always"}'),

('AP-HIVE-PARTITION-EXPLOSION', 'Hive partition explosion',
 'Too many partitions degrade Metastore performance and planning time.',
 'Performance', 'Hive', 'Hive',
 '["Slow query planning", "Metastore overwhelmed"]',
 '["Unbounded partition creation"]',
 '["Hive"]',
 'Tables with millions of partitions cause multi-minute query planning and Metastore OOM.',
 'MEDIUM', 'WARNING',
 '["Limit dynamic partitions: hive.exec.max.dynamic.partitions=10000", "Use composite partitioning (year/month, not year/month/day/hour)", "Implement partition retention: drop partitions older than N days", "Monitor partition count per table"]',
 '{"type": "always"}'),

('AP-ZOMBIE-CONTAINERS', 'Zombie YARN containers',
 'Orphaned containers consume resources but produce no useful work.',
 'Performance', 'Yarn', 'Yarn',
 '["Resource waste"]',
 '["Container leak from failed applications"]',
 '["Yarn"]',
 'Zombie containers reduce available cluster capacity without any productivity.',
 'MEDIUM', 'WARNING',
 '["Monitor container lifecycle: running containers without parent application", "Configure YARN container timeout: yarn.nodemanager.delete.debug-delay-sec", "Implement periodic cleanup of orphaned application directories", "Check for YARN app -status for suspicious long-running apps"]',
 '{"type": "always"}'),

('AP-STALE-TEMP-DATA', 'Stale temporary data cleanup',
 'HDFS /tmp, staging directories, and Spark scratch accumulate stale data over time.',
 'Performance', 'HDFS', 'HDFS',
 '["Storage waste"]',
 '["No temp data cleanup"]',
 '["HDFS"]',
 'Temporary directories can grow to terabytes of abandoned job output and shuffle data.',
 'LOW', 'WARNING',
 '["Schedule cleanup of /tmp/hive, /tmp/hadoop-yarn/staging older than 7 days", "Clean Spark event logs: retain last 30 days", "Configure HDFS trash with reasonable retention (24-48h)", "Monitor /tmp and staging directory sizes weekly"]',
 '{"type": "always"}'),

-- ============================================================
-- INFRASTRUCTURE & HARDWARE
-- ============================================================

('INFRA-SMART-HEALTH', 'SMART disk health monitoring',
 'SMART attributes predict disk failures. Reallocated sectors are an early warning sign.',
 'Architecture', 'Hardware', 'OS',
 '["Disk failure causing data loss"]',
 '["No SMART monitoring"]',
 '["Servers", "HDFS"]',
 'Disks with reallocated sectors fail at 14x the rate of healthy disks.',
 'MEDIUM', 'WARNING',
 '["Install smartmontools on all nodes", "Monitor: Reallocated_Sector_Ct, Current_Pending_Sector, Offline_Uncorrectable", "Alert when any of these counters > 0", "Replace disks proactively when SMART indicates degradation"]',
 '{"type": "always"}'),

('INFRA-DMESG-ERRORS', 'Hardware errors in dmesg',
 'Kernel messages about I/O errors, ECC corrections, and hardware failures indicate failing components.',
 'Architecture', 'Hardware', 'OS',
 '["Data corruption", "Service crashes"]',
 '["Hardware failures not detected"]',
 '["Servers"]',
 'Ignored dmesg errors escalate from correctable to uncorrectable, causing data loss or crashes.',
 'MEDIUM', 'CRITICAL',
 '["Parse dmesg daily for: I/O error, ECC, mce, hardware error, ata errors", "Alert on any hardware-related error", "Investigate and replace affected hardware promptly", "Correlate with SMART data for disk issues"]',
 '{"type": "list_not_empty", "path": "infra_diagnostics.dmesg_errors"}'),

('INFRA-CPU-GOVERNOR', 'CPU performance governor',
 'CPU governor should be set to performance for Hadoop nodes to avoid frequency scaling latency.',
 'Performance', 'Hardware', 'OS',
 '["Latency spikes from frequency scaling"]',
 '["Power-saving governor active"]',
 '["Servers"]',
 'Ondemand/powersave governors add microseconds of latency on every frequency ramp-up.',
 'LOW', 'WARNING',
 '["Set governor to performance: cpupower frequency-set -g performance", "Persist via: GOVERNOR=performance in /etc/sysconfig/cpupower", "Verify: cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor", "Disable in BIOS: Intel SpeedStep, AMD Cool n Quiet"]',
 '{"type": "metadata_check", "path": "infra_diagnostics.cpu_power.governor", "operator": "equals", "expected": "performance"}'),

('INFRA-VM-OVERHEAD', 'Virtualization overhead detection',
 'Virtual machines add overhead from hypervisor scheduling. Detect and account for it.',
 'Performance', 'Hardware', 'OS',
 '["Unpredictable performance from VM scheduling"]',
 '["VM overhead not accounted for"]',
 '["Servers"]',
 'VM CPU steal time and memory balloon drivers can cause severe performance degradation.',
 'MEDIUM', 'WARNING',
 '["Check if running in VM: infra_diagnostics.virtualization.is_virtual", "Monitor CPU steal time: threshold >5% is problematic", "Disable memory ballooning for Hadoop VMs", "Request dedicated CPU cores (pinning) from hypervisor team"]',
 '{"type": "metadata_check", "path": "infra_diagnostics.virtualization.is_virtual", "operator": "equals", "expected": true}'),

('INFRA-NUMA-BALANCE', 'NUMA balancing configuration',
 'Automatic NUMA balancing can cause performance variability. Disable for latency-sensitive services.',
 'Performance', 'Hardware', 'OS',
 '["Performance variability"]',
 '["NUMA balancing causing memory migration"]',
 '["Servers"]',
 'NUMA balancing migrates memory pages between nodes, causing latency spikes for HBase and Impala.',
 'LOW', 'INFO',
 '["Disable for latency-sensitive workloads: echo 0 > /proc/sys/kernel/numa_balancing", "Use numactl --interleave=all for JVM processes spanning NUMA nodes", "Monitor NUMA hit/miss ratio: numastat", "Consider NUMA-aware JVM flags: -XX:+UseNUMA"]',
 '{"type": "always"}'),

-- ============================================================
-- ECOSYSTEM INTEGRATIONS
-- ============================================================

('KNOX-AUTH', 'Knox authentication provider',
 'Knox must be configured with a proper authentication provider (LDAP/Kerberos) for production.',
 'Security', 'Authentication', 'Knox',
 '["Unauthorized access via Knox"]',
 '["Default authentication provider"]',
 '["Knox"]',
 'Default ShiroProvider with static users is insecure for production.',
 'HIGH', 'CRITICAL',
 '["Configure LDAP or Kerberos (PAM) authentication in Knox topology", "Set up SSO with SAML/OAuth2 for web UIs", "Remove default users from ShiroProvider", "Enable audit logging for all Knox-proxied requests"]',
 '{"type": "always"}'),

('KNOX-SSL', 'Knox SSL certificate',
 'Knox gateway must use a trusted SSL certificate, not the self-signed default.',
 'Security', 'Data Protection', 'Knox',
 '["Man-in-the-middle attacks", "Browser security warnings"]',
 '["Self-signed certificate"]',
 '["Knox"]',
 'Self-signed certs cause browser warnings and are vulnerable to MITM when clients skip verification.',
 'MEDIUM', 'WARNING',
 '["Replace self-signed cert with CA-signed certificate", "Configure gateway.tls.keystore.path and gateway.tls.key.alias", "Set certificate renewal reminders", "Enable HSTS in Knox for web UIs"]',
 '{"type": "always"}'),

('LIVY-SESSION-CLEANUP', 'Livy session cleanup',
 'Orphaned Livy sessions consume YARN resources indefinitely if not cleaned up.',
 'Performance', 'Spark', 'Spark',
 '["Resource leak"]',
 '["No session timeout or cleanup"]',
 '["Yarn"]',
 'Each orphaned Livy session holds a YARN application with allocated containers doing nothing.',
 'MEDIUM', 'WARNING',
 '["Configure livy.server.session.timeout=3600s (1 hour idle timeout)", "Set livy.server.session.max-creation to limit concurrent sessions", "Monitor Livy session count and kill orphans", "Implement client-side session cleanup in application code"]',
 '{"type": "always"}'),

('LIVY-RESOURCE-LIMITS', 'Livy resource limits per session',
 'Each Livy session should have bounded resource allocation to prevent one user from consuming all resources.',
 'Performance', 'Spark', 'Spark',
 '["Resource starvation"]',
 '["No per-session limits"]',
 '["Yarn", "Spark"]',
 'Without limits, a single Livy session can request hundreds of executors.',
 'MEDIUM', 'WARNING',
 '["Set livy.rsc.jars.max-size per session", "Configure YARN queue restrictions for Livy sessions", "Set spark.dynamicAllocation.maxExecutors in Livy defaults", "Monitor per-session resource consumption"]',
 '{"type": "always"}'),

('METASTORE-DB-BACKUP', 'Hive Metastore database backup',
 'The Metastore database contains all table definitions. Its loss means losing all metadata.',
 'Architecture', 'Hive', 'Hive',
 '["Complete metadata loss"]',
 '["No Metastore DB backup"]',
 '["Hive", "Data"]',
 'Without Metastore backup, a database failure loses all table definitions, schemas, and partition information.',
 'HIGH', 'CRITICAL',
 '["Configure automated daily backup of Metastore DB (mysqldump/pg_dump)", "Store backups in a separate location (not the same cluster)", "Test restore procedure quarterly", "Monitor backup job success/failure"]',
 '{"type": "always"}'),

('METASTORE-DB-CONN-POOL', 'Metastore connection pool',
 'Connection pool exhaustion causes Hive/Spark/Impala query failures.',
 'Performance', 'Hive', 'Hive',
 '["Query failures from connection timeout"]',
 '["Default connection pool too small"]',
 '["Hive"]',
 'With many concurrent HS2/Impala sessions, the default pool (10) is quickly exhausted.',
 'MEDIUM', 'WARNING',
 '["Set datanucleus.connectionPool.maxPoolSize=50 in hive-site.xml", "Set datanucleus.connectionPoolingType=HikariCP for better performance", "Monitor connection pool usage in database (SHOW PROCESSLIST)", "Scale pool size with number of concurrent sessions"]',
 '{"type": "always"}'),

('LDAP-SYNC-FREQ', 'LDAP synchronization frequency',
 'Ranger UserSync and other LDAP consumers should sync frequently enough to reflect permission changes.',
 'Security', 'Authentication', 'Platform',
 '["Stale user/group permissions"]',
 '["Sync too infrequent"]',
 '["Ranger"]',
 'If sync runs daily, a new employee waits up to 24h for access; a terminated employee retains access.',
 'MEDIUM', 'WARNING',
 '["Configure Ranger UserSync interval to 1 hour or less", "Set ranger.usersync.sleeptimeinmillisbetweensynccycle=3600000", "Monitor sync logs for failures", "Implement immediate sync trigger for critical changes (terminations)"]',
 '{"type": "always"}'),

('LDAP-FAILOVER', 'LDAP/AD failover configuration',
 'LDAP client configuration should include multiple servers for high availability.',
 'Architecture', 'High Availability', 'Platform',
 '["Authentication failure when LDAP server is down"]',
 '["Single LDAP server configured"]',
 '["Servers"]',
 'A single LDAP server is a SPOF for all authentication across the cluster.',
 'MEDIUM', 'WARNING',
 '["Configure multiple LDAP URIs: ldap://dc1.example.com ldap://dc2.example.com", "Use SRV DNS records for automatic DC discovery", "Test failover by stopping primary LDAP server", "Configure LDAP connection timeout and retry"]',
 '{"type": "always"}');
